x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  vpn:
    image: qmcgaw/gluetun:latest@sha256:b0ee2135e6ba52ad3f102aae9663707cd1c9531485117067a380d3b2b6dd991d
    container_name: deluge-vpn
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      VPN_TYPE: openvpn
      # Get credentials from https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/service-credentials/
      OPENVPN_USER: "${OPENVPN_USER}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      SERVER_HOSTNAMES: "${CONNECT}.nordvpn.com"
    ports:
      # - "8112:8112"
      - "58846:58846"
    networks:
      - web_bridge
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.seedbox.rule: Host(`seedbox.int.saphnet.xyz`)
      traefik.http.routers.seedbox.entrypoints: websecure
      traefik.http.routers.seedbox.tls: "true"
      traefik.http.routers.seedbox.tls.certresolver: letsencrypt
      traefik.http.routers.seedbox.tls.domains[0].main: seedbox.int.saphnet.xyz
      traefik.http.routers.seedbox.service: seedbox-svc
      traefik.http.services.seedbox-svc.loadBalancer.server.port: "8112"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - "8112"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only

  deluge:
    image: ghcr.io/linuxserver/deluge:2.2.0@sha256:33a939576f7ecfc1227db1a0cb2afce030ce983e620ec9d93c956e3700e21fe9 # To only update intentionally
    container_name: deluge
    depends_on:
      vpn:
        condition: service_healthy
    volumes:
      - deluge-config:/config
      - seedbox-files:/seedbox-data
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
      DELUGE_LOGLEVEL: error
    network_mode: service:vpn
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  deluge-sftp:
    image: ghcr.io/anarchobooleanism/saphnet-sftp:v0.1.1@sha256:bb164f405864b029fd3b3e5501bb347de0acd8a54436b3ffc79b9b456e3ce152
    container_name: deluge-sftp
    volumes:
      - sftp-ssh-data:/etc/ssh # For persistence of keys
      - seedbox-files:/home/seedbox/sftp
    environment:
      SFTP_USERNAME: seedbox
      SFTP_PASSWORD: "${SFTP_PASSWORD}"
    ports:
      - "2222:22"
    restart: unless-stopped

volumes:
  # tailscale-config:
  deluge-config:
  sftp-ssh-data:
  seedbox-files:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/deluge"

networks:
  web_bridge:
    name: web_bridge
    external: true
