services:
  speedtest:
    image: openspeedtest/latest:v2.0.6@sha256:a6a7e3b3e9e93cfe7b9b2eb49c60b2a93644149a0a600845d4df57148b193ff6
    container_name: openspeedtest
    ports:
      - "3000:3000"
      - "3001:3001"
    labels:
      traefik.enable: "true"
      traefik.http.routers.speedtest.rule: Host(`speedtest.int.saphnet.xyz`)
      traefik.http.routers.speedtest.entrypoints: websecure
      traefik.http.routers.speedtest.tls: "true"
      traefik.http.routers.speedtest.tls.certresolver: letsencrypt
      traefik.http.routers.speedtest.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.speedtest.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.speedtest.service: speedtest-svc
      traefik.http.services.speedtest-svc.loadBalancer.server.port: "3000"
    networks:
      - web_bridge
    restart: unless-stopped

networks:
  web_bridge:
    name: web_bridge
    external: true
