# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: AnarchoBooleanism
    password: ${{secrets.GHCR_TOKEN}}
    replaces-base: true
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: anarchobooleanism
    password: ${{secrets.DOCKERHUB_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    open-pull-requests-limit: 64 # We have a lot of packages, so we need to be able to have a lot of pull requests
    registries: "*"
    directories: # Avoiding ** for now, so doing directories and direct subdirectories will do
      - "/stacks/*/"
      - "/stacks/*/*/"
    groups:
      guacamole:
        patterns:
          - "guacamole/guacd"
          - "guacamole/guacamole"
      immich:
        patterns:
          - "immich-app/immich-server"
          - "immich-app/immich-machine-learning"
      media-server: # Grouping everything together for simplicity
        patterns:
          - "linuxserver/bazarr"
          - "linuxserver/prowlarr"
          - "linuxserver/radarr"
          - "linuxserver/sonarr"
          - "flaresolverr/flaresolverr"
          - "recyclarr/recyclarr"
          - "seerr-team/seerr"
          - "jellyfin/jellyfin"
      n8n:
        patterns:
          - "anarchobooleanism/n8n-homepage-api"
          - "n8nio/n8n"
          - "n8nio/runners"
      pyrodactyl:
        patterns:
          - "pyrodactyl-oss/pyrodactyl"
          - "pyrohost/elytra"
      vert:
        patterns:
          - "vert-sh/vert"
          - "vert-sh/vertd"
    schedule:
      interval: "weekly"
