keys:
  - &admin age1ute399nzja7le5um48rzdg2nj4c7rf5jvhj7slh05mt5x79nr4wqqlwkdj
  - &control_server age1kc55vw25m24cqt67kfl8806eq8kqpxa8tlal4kl0yay29z3jj5us4jr5je
  - &docker-host-core age1c54f3t2j9qdtwffyp2k8wfs27uquu66cgk2a8frwmrwdz6ds8c2syxfcd6
  - &docker-host-pve3 age1zswt40z370tmt8v83w7tcd2qaa93fa3ame0rd3am9vwe7fsung2s03y3uu
  - &docker-host-pve4 age1027xeu6vnc4evypdkakgvj0u30eqtz2r8ljdgz8v3dhsvfz8zgxsu0gr3x
  - &vps1 age18xl6zml7fza9e3n0gn99yymzkjrzddax3n3t2r7zlw0vjd60049qnldus7
creation_rules:
  - path_regex: (^|\/)secrets\/control-server\.yaml$ # Control server
    key_groups:
    - age:
      - *admin
      - *control_server
  - path_regex: (^|\/)secrets\/docker-host-core\.yaml$ # docker-host-core
    key_groups:
    - age:
      - *admin
      - *docker-host-core
  - path_regex: (^|\/)secrets\/docker-host-pve3\.yaml$ # docker-host-pve3
    key_groups:
    - age:
      - *admin
      - *docker-host-pve3
  - path_regex: (^|\/)secrets\/docker-host-pve4\.yaml$ # docker-host-pve4
    key_groups:
    - age:
      - *admin
      - *docker-host-pve4
  - path_regex: (^|\/)secrets\/vps1\.yaml$ # vps1
    key_groups:
    - age:
      - *admin
      - *vps1
