## Stack-related procedures

[[procedure]]
name = "docker-host-pve3_redeploy-changed"
description = "A procedure that redeploys all IaC stacks that have had changes to their config or config files, for docker-host-pve3."
tags = ["redeploy-changed", "iac"]

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [ # Make sure to give all the names of all stacks here!
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = """
deluge-seedbox
docker-proxy-pve3
docker-volume-rclone-pve3
foldingathome
glances-pve3
immich
media-server
traefik-pve3
vertd
""", enabled = true }
]

## Stacks

# deluge-seedbox
[[stack]]
name = "deluge-seedbox"
description = "A torrent client for file sharing, behind a VPN, and an SFTP server for accessing these files."
tags = ["iac"]
[stack.config]
server = "docker-host-pve3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/deluge-seedbox"
config_files = [
  { path = "secrets/docker-host-pve3.enc.env", requires = "Redeploy" }
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-pve3.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
"""

# docker-proxy
[[stack]]
name = "docker-proxy-pve3"
description = "Used as a way to access the internal Docker socket from outside (read-only), mostly by Homepage."
tags = ["docker-proxy", "iac"]
[stack.config]
server = "docker-host-pve3"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-proxy"

# docker-volume-rclone
[[stack]]
name = "docker-volume-rclone-pve3"
description = "A solution for regularly cloning Docker volumes to a remote NFS location."
tags = ["docker-volume-rclone", "iac"]
[stack.config]
server = "docker-host-pve3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-volume-rclone"
file_paths = [
  "base.yaml",
  "docker-host-pve3.yaml"
]

# foldingathome
[[stack]]
name = "foldingathome"
description = "A program donating computing resources to science by simulating protein folding."
tags = ["iac", "gpu"]
[stack.config]
server = "docker-host-pve3"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/foldingathome"
config_files = [
  { path = "secrets/docker-host-pve3.enc.env", requires = "Redeploy" }
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-pve3.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
"""

# glances
[[stack]]
name = "glances-pve3"
description = "A real-time monitoring tool for systems (e.g. processes and hardware usage), equivalent to top/htop."
tags = ["glances", "iac"]
[stack.config]
server = "docker-host-pve3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/glances"
file_paths = ["compose.yaml", "docker-host-pve3.yaml"]

# immich
[[stack]]
name = "immich"
description = "A self-hosted photo and video management solution."
tags = ["iac", "gpu"]
[stack.config]
server = "docker-host-pve3"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/immich"
config_files = [
  { path = "extra/hwaccel.ml.yaml", requires = "Redeploy" },
  { path = "extra/hwaccel.transcoding.yaml", requires = "Redeploy" },
  { path = "secrets/docker-host-pve3.enc.env", requires = "Redeploy" },
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-pve3.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
TAILSCALE_IP = '[[TAILSCALE_IP_PVE3]]'
"""

# media-server
[[stack]]
name = "media-server"
description = "A media server designed to integrate with the Deluge Seedbox, using Jellyfin, Jellyseerr, Prowlarr (suported with Flaresolverr), Radarr & Sonarr (supported with Recyclarr), and Bazarr. Note that there are two groups of Radarr/Sonarr-related containers, for anime and non-anime media."
tags = ["iac", "gpu"]
[stack.config]
server = "docker-host-pve3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/media-server"
environment = """
TAILSCALE_IP = '[[TAILSCALE_IP_PVE3]]'
"""

# traefik
[[stack]]
name = "traefik-pve3"
description = "A cloud-native reverse proxy and load balancer."
tags = ["traefik", "iac"]
[stack.config]
server = "docker-host-pve3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/traefik"
file_paths = [
  "base.yaml",
  "docker-host-pve3.yaml"
]
environment = """
NAMECHEAP_API_USER = '[[NAMECHEAP_USERNAME]]'
NAMECHEAP_API_KEY = '[[NAMECHEAP_API_KEY]]'
ACME_EMAIL = '[[CERTBOT_EMAIL]]'
DASHBOARD_PASSWORD = '[[TRAEFIK_DASHBOARD_PASSWORD]]'
DASHBOARD_LOGIN = '[[TRAEFIK_DASHBOARD_LOGIN]]'
"""

# vertd
[[stack]]
name = "vertd"
description = "The daemon that handles video conversions for the VERT.sh service, with GPU acceleration."
tags = ["vert", "iac", "gpu"]
[stack.config]
server = "docker-host-pve3"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/vertd"

