# docker-proxy
[[stack]]
name = "docker-proxy-pve4"
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-proxy"

# docker-volume-rclone
[[stack]]
name = "docker-volume-rclone-pve4"
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-volume-rclone"
file_paths = [
  "base.yaml",
  "docker-host-pve4.yaml"
]

# glances
[[stack]]
name = "glances-pve4"
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/glances"
file_paths = ["docker-host-pve4.yaml"]

# pterodactyl/wing
[[stack]]
name = "pterodactyl-wing-pve4"
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/pterodactyl/wing"
file_paths = ["docker-host-pve4.yaml"]
environment = """
DNS_NAMECHEAP_USERNAME = [[NAMECHEAP_USERNAME]]
DNS_NAMECHEAP_API_KEY = [[NAMECHEAP_API_KEY]]
CERTBOT_EMAIL = [[CERTBOT_EMAIL]]
"""

# traefik
[[stack]]
name = "traefik-pve4"
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/traefik"
file_paths = [
  "base.yaml",
  "docker-host-pve4.yaml"
]
environment = """
NAMECHEAP_API_USER = [[NAMECHEAP_USERNAME]]
NAMECHEAP_API_KEY = [[NAMECHEAP_API_KEY]]
ACME_EMAIL = [[CERTBOT_EMAIL]]
DASHBOARD_PASSWORD = [[TRAEFIK_DASHBOARD_PASSWORD]]
DASHBOARD_LOGIN = "[[TRAEFIK_DASHBOARD_LOGIN]]"
"""

