## Stack-related procedures

[[procedure]]
name = "docker-host-pve4_redeploy-changed"
description = "A procedure that redeploys all IaC stacks that have had changes to their config or config files, for docker-host-pve4."
tags = ["redeploy-changed", "iac"]

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [ # Make sure to give all the names of all stacks here!
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = """
docker-proxy-pve4
docker-volume-rclone-pve4
glances-pve4
pterodactyl-wing-pve4
traefik-pve4
""", enabled = true }
]

## Stacks

# docker-proxy
[[stack]]
name = "docker-proxy-pve4"
description = "Used as a way to access the internal Docker socket from outside (read-only), mostly by Homepage."
tags = ["docker-proxy", "iac"]
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-proxy"

# docker-volume-rclone
[[stack]]
name = "docker-volume-rclone-pve4"
description = "A solution for regularly cloning Docker volumes to a remote NFS location."
tags = ["docker-volume-rclone", "iac"]
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-volume-rclone"
file_paths = [
  "base.yaml",
  "docker-host-pve4.yaml"
]

# glances
[[stack]]
name = "glances-pve4"
description = "A real-time monitoring tool for systems (e.g. processes and hardware usage), equivalent to top/htop."
tags = ["glances", "iac"]
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/glances"
file_paths = ["compose.yaml", "docker-host-pve4.yaml"]

# pterodactyl/wing
[[stack]]
name = "pterodactyl-wing-pve4"
description = "A server control plane for the Pterodactyl panel."
tags = ["pterodactyl", "iac"]
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/pterodactyl/wing"
file_paths = ["docker-host-pve4.yaml"]
environment = """
DNS_NAMECHEAP_USERNAME = '[[NAMECHEAP_USERNAME]]'
DNS_NAMECHEAP_API_KEY = '[[NAMECHEAP_API_KEY]]'
CERTBOT_EMAIL = '[[CERTBOT_EMAIL]]'
"""

# traefik
[[stack]]
name = "traefik-pve4"
description = "A cloud-native reverse proxy and load balancer."
tags = ["traefik", "iac"]
[stack.config]
server = "docker-host-pve4"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/traefik"
file_paths = [
  "base.yaml",
  "docker-host-pve4.yaml"
]
environment = """
NAMECHEAP_API_USER = '[[NAMECHEAP_USERNAME]]'
NAMECHEAP_API_KEY = '[[NAMECHEAP_API_KEY]]'
ACME_EMAIL = '[[CERTBOT_EMAIL]]'
DASHBOARD_PASSWORD = '[[TRAEFIK_DASHBOARD_PASSWORD]]'
DASHBOARD_LOGIN = '[[TRAEFIK_DASHBOARD_LOGIN]]'
"""

