## Stack-related procedures

[[procedure]]
name = "docker-host-core_redeploy-changed"
description = "A procedure that redeploys all IaC stacks that have had changes to their config or config files, for docker-host-core."
tags = ["redeploy-changed", "iac"]

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [ # Make sure to give all the names of all stacks here!
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = """
docker-volume-rclone-core
filestash
glances-core
guacamole
homepage
n8n
netbootxyz
openspeedtest-nginx
pterodactyl-panel
traefik-core
vert-sh
""", enabled = true }
]

## Stacks

# docker-volume-rclone
[[stack]]
name = "docker-volume-rclone-core"
description = "A solution for regularly cloning Docker volumes to a remote NFS location."
tags = ["docker-volume-rclone", "iac"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-volume-rclone"
file_paths = [
  "base.yaml",
  "docker-host-core.yaml"
]

# filestash
[[stack]]
name = "filestash"
description = "A way to access various file servers via web UI."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/filestash"

# glances
[[stack]]
name = "glances-core"
description = "A real-time monitoring tool for systems (e.g. processes and hardware usage), equivalent to top/htop."
tags = ["glances", "iac"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/glances"
file_paths = ["docker-host-core.yaml"]
config_files = [
  { path = "compose.yaml", requires = "Redeploy" }
]

# guacamole
[[stack]]
name = "guacamole"
description = "A way to remotely access other machines via web UI."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/guacamole"

# homepage
[[stack]]
name = "homepage"
description = "A way to see the status of various services in one webpage."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/homepage"
config_files = [
  { path = "secrets/docker-host-core.enc.env", requires = "Redeploy" }
]
registry_provider = "ghcr.io"
registry_account = "AnarchoBooleanism"
# We do it this way since the Compose config leaves out environment variables,
# instead expecting us to give a path to a .env file with variables to give the service
compose_cmd_wrapper = "sops exec-file --no-fifo secrets/docker-host-core.enc.env 'export SOPS_SECRETS_PATH={} && [[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
HOMEPAGE_VAR_TRAEFIK_PASSWORD='[[TRAEFIK_DASHBOARD_PASSWORD]]'
"""

# n8n
[[stack]]
name = "n8n"
description = "A workflow automation platform, with the flexibility of code and the speed of no-code."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/n8n"
config_files = [
  { path = "secrets/docker-host-core.enc.env", requires = "Redeploy" },
  { path = "init-data.sh", requires = "Restart" }
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-core.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
MAIL_PASSWORD = '[[NAMECHEAP_MAIL_PASSWORD]]'
TAILSCALE_IP = '[[TAILSCALE_IP_CORE]]'
"""

# netbootxyz
[[stack]]
name = "netbootxyz"
description = "A host for providing network access to different operating systems via PXE and HTTP."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/netbootxyz"
config_files = [
  { path = "secrets/docker-host-core.enc.env", requires = "Redeploy" },
  { path = "local-vars.ipxe", requires = "Restart" }
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-core.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
"""

# openspeedtest
[[stack]]
name = "openspeedtest-nginx"
description = "A web tool for determining the speed and latency of a connection."
tags = ["iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/openspeedtest"

# pterodactyl/panel
[[stack]]
name = "pterodactyl-panel"
description = "A server management panel for games, e.g. Minecraft."
tags = ["pterodactyl", "iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/pterodactyl/panel"
config_files = [
  { path = "secrets/docker-host-core.enc.env", requires = "Redeploy" }
]
compose_cmd_wrapper = "sops exec-env secrets/docker-host-core.enc.env '[[COMPOSE_COMMAND]]'"
compose_cmd_wrapper_include = ["up", "config", "build", "pull", "run"]
environment = """
MAIL_PASSWORD = '[[NAMECHEAP_MAIL_PASSWORD]]'
RUSTIC_S3_REGION = '[[SAPHNET_S3_SERVER_REGION]]'
RUSTIC_S3_ACCESS_KEY_ID = '[[PTERODACTYL_BACKUP_S3_KEY_ID]]'
RUSTIC_S3_SECRET_ACCESS_KEY = '[[PTERODACTYL_BACKUP_S3_ACCESS_KEY]]'
RUSTIC_S3_BUCKET = '[[PTERODACTYL_BACKUP_S3_BUCKET_NAME]]'
RUSTIC_S3_ENDPOINT = '[[SAPHNET_S3_SERVER_ENDPOINT]]'
"""

# traefik
[[stack]]
name = "traefik-core"
description = "A cloud-native reverse proxy and load balancer."
tags = ["traefik", "iac"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/traefik"
file_paths = [
  "base.yaml",
  "docker-host-core.yaml"
]
environment = """
NAMECHEAP_API_USER = '[[NAMECHEAP_USERNAME]]'
NAMECHEAP_API_KEY = '[[NAMECHEAP_API_KEY]]'
ACME_EMAIL = '[[CERTBOT_EMAIL]]'
DASHBOARD_PASSWORD = '[[TRAEFIK_DASHBOARD_PASSWORD]]'
DASHBOARD_LOGIN = '[[TRAEFIK_DASHBOARD_LOGIN]]'
"""

# vert-sh
[[stack]]
name = "vert-sh"
description = "A web interface for handling the conversion of different file formats."
tags = ["vert", "iac", "high-availability"]
[stack.config]
server = "docker-host-core"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/vert-sh"

