x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  # vpn:
  #   image: tailscale/tailscale:latest
  #   container_name: vpn
  #   cap_add:
  #     - net_admin
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   environment:
  #     TS_AUTHKEY: XXX
  #     TS_EXTRA_ARGS: --exit-node=XXX
  #     TS_STATE_DIR: /var/lib/tailscale
  #     TS_USERSPACE: false
  #     TS_HOSTNAME: deluge-seedbox
  #   ports:
  #     - "8112:8112"
  #     - "58846:58846"
  #   volumes:
  #     - tailscale-config:/var/lib/tailscale
  #   restart: unless-stopped
  #
  # vpn:
  #   image: ghcr.io/bubuntux/nordvpn@sha256:ac521b5a8d1387780d812a0ed46dd23aa3ee5e47d6d9f9eace39213ea1f56509
  #   container_name: vpn
  #   cap_add:
  #     - NET_ADMIN               # Required
  #     - NET_RAW                 # Required
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  #   ports:
  #     - "8112:8112"
  #     - "58846:58846"
  #   environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
  #     TECHNOLOGY: NordLynx
  #     NETWORK: "192.168.0.0/16"  # So it can be accessed within the local network
  #     # Secrets to set in environment:
  #     TOKEN: "$TOKEN"
  #     CONNECT: "$CONNECT"
  #   healthcheck: # Make sure it can access the internet
  #     test: ["CMD", "curl", "-f", "https://www.google.com"]
  #     interval: "30s"
  #     timeout: "10s"
  #     retries: 3
  #     start_period: "15s" # Give the VPN time to establish the initial connection
  #   restart: unless-stopped
  
  vpn:
    image: qmcgaw/gluetun:v3.41.0
    container_name: vpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8112:8112"
      - "58846:58846"
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      VPN_TYPE: openvpn
      # Get credentials from https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/service-credentials/
      OPENVPN_USER: "${OPENVPN_USER}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      SERVER_HOSTNAMES: "${CONNECT}.nordvpn.com"
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
      DELUGE_LOGLEVEL: error
    volumes:
      - deluge-config:/config
      - seedbox-files:/seedbox-data
    network_mode: container:vpn
    depends_on:
      vpn:
        condition: service_healthy
    restart: unless-stopped

  deluge-sftp:
    image: ghcr.io/anarchobooleanism/saphnet-sftp:v0.1.1
    container_name: deluge-sftp
    ports:
      - "2222:22"
    environment:
      SFTP_USERNAME: seedbox
      SFTP_PASSWORD: "${SFTP_PASSWORD}"
    volumes:
      - sftp-ssh-data:/etc/ssh # For persistence of keys
      - seedbox-files:/home/seedbox/sftp
    restart: unless-stopped

volumes:
  # tailscale-config:
  deluge-config:
  sftp-ssh-data:
  seedbox-files:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/deluge"
