debug: false
uuid: 36a0bd06-9a27-424a-8ff1-352b88b472dc
token_id: RJ1EQX8El47BwXRP
token: 5rOYwU7GJwTmkjq4u8jwqOYKbPGfhjbDaPgDjS8VoOZLsObv4D1fDjie4u2CLm76
api:
  host: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/fullchain.pem
    key: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://pterodactyl.int.saphnet.xyz'