debug: false
uuid: 5464a866-5132-4dfe-8a0b-677f9c1cb057
token_id: IuIXFxt7yp19zL65
token: ytOjkm5HBIGkSrBt9V2V9l8103LZJgQkdRPWVJVL7PQpQzzTVaDYWC4v94HGr6I8
api:
  host: 0.0.0.0
  port: 8443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/fullchain.pem
    key: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://pterodactyl.int.saphnet.xyz'
docker:
  network:
    interfaces:
      v4:
        subnet: "10.55.230.0/24"
        gateway: 10.55.230.0