debug: false
uuid: 258a579e-b414-43b4-835a-7d3fd408d276
token_id: t0ywv6pGcEHESNGG
token: JDTWmM5qoeHiFVTE8McBrdoRpqIus9lCip2caMd6yNQAYlmE6IFDddx6TVpT0EfN
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/fullchain.pem
    key: /etc/letsencrypt/live/pterodactyl-node-main.int.saphnet.xyz/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://pterodactyl.int.saphnet.xyz'
docker:
  network:
    interfaces:
      v4:
        subnet: "10.55.230.0/24"
        gateway: 10.55.230.1