services:
  guacdb:
    container_name: guacamoledb
    image: mariadb:12@sha256:3ba727e641ef0ea24054e47c72a831b1067da32d5139c0405b629c25b115eb89
    environment:
      MYSQL_ROOT_PASSWORD: MariaDBRootPass
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: MariaDBUserPass
    volumes:
      - guac-db-data:/var/lib/mysql
    networks:
      - web_bridge
    restart: unless-stopped

  guacd:
    container_name: guacd
    image: guacamole/guacd:latest@sha256:65e8fd8cce7d061d7e012c1cbd31330e948638002bf592e132bbaf397d83b971
    networks:
      - web_bridge
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:latest@sha256:62a075b86676c7094a21b545f96778a50e052b284c700c30d3e00e46117c8e7f
    depends_on:
      - guacdb
      - guacd
    # ports:
    #   - "8080:8080"
    labels:
      traefik.enable: "true"
      traefik.http.routers.guacamole.rule: Host(`guacamole.int.saphnet.xyz`) && PathPrefix(`/guacamole/`)
      traefik.http.routers.guacamole.entrypoints: websecure
      traefik.http.routers.guacamole.tls: "true"
      traefik.http.routers.guacamole.tls.certresolver: letsencrypt
      traefik.http.routers.guacamole.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.guacamole.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.guacamole.service: guacamole-svc
      traefik.http.services.guacamole-svc.loadBalancer.server.port: "8080"
      # Root directory redirect
      traefik.http.routers.guacamole-root.rule: Host(`guacamole.int.saphnet.xyz`) && Path(`/`)
      traefik.http.routers.guacamole-root.entrypoints: websecure
      traefik.http.routers.guacamole-root.tls: "true"
      traefik.http.routers.guacamole-root.tls.certresolver: letsencrypt
      traefik.http.routers.guacamole-root.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.guacamole-root.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.guacamole-root.middlewares: guacamole-root-redirect
      traefik.http.middlewares.guacamole-root-redirect.redirectregex.regex: "^https?://(.*)/$"
      traefik.http.middlewares.guacamole-root-redirect.redirectregex.replacement: "https://$${1}/guacamole/"
      traefik.http.middlewares.guacamole-root-redirect.redirectregex.permanent: "true"
      traefik.http.routers.guacamole-root.service: guacamole-svc
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacdb
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: MariaDBUserPass
      # TOTP_ENABLE: true
    networks:
      - web_bridge
    restart: unless-stopped

volumes:
  guac-db-data:

networks:
  web_bridge:
    name: web_bridge
    external: true
