# Configuration for Pterodactyl wings, to be paired with the panel
# This is intended to be used on docker-host-pve4, though it still relies on the reverse proxy

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node

services:
  wings: # TODO: Create automatic backup script
    image: ghcr.io/pterodactyl/wings:v1.11.13
    restart: unless-stopped
    networks:
      - ptero0
    ports:
      - "8443:443" # Is port 8443 on this IP, but 443 on the inside and 443 on the reverse proxy
      - "2022:2022" # SFTP port
    tty: true
    environment:
      TZ: "America/Los_Angeles"
      # For ease of setup, this is going to use root user.
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - wings-config:/etc/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - wings-logs:/var/log/pterodactyl
      - /tmp/pterodactyl:/tmp/pterodactyl

volumes:
  wings-config:
  wings-logs:

# This is Wings' Network. We don't need much depth here, all you need to know, is
# that it allows the passthrough of the ports from Wings.
networks:
  ptero0:
    name: ptero0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ptero0