# Configuration for Pterodactyl wings, to be paired with the panel
# This is intended to be used on docker-host-pve4

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node
#                         https://dev.to/marrouchi/the-challenge-about-ssl-in-docker-containers-no-one-talks-about-32gh

# Be sure to define
# - DNS_NAMECHEAP_USERNAME
# - DNS_NAMECHEAP_API_KEY
# - CERTBOT_EMAIL

x-common:
  INSTANCE_DOMAIN: &instance-domain "pterodactyl-node-main.int-net.saphnet.xyz"

services:
  wing:
    container_name: pterodactyl-wing # Refer to the panel container this way
    image: ghcr.io/pyrohost/elytra:1.3.0
    restart: unless-stopped
    networks:
      - ptero0
      - pterodactyl_wing_internal
    ports:
      # - "8443:443" # Is port 8443 on this IP, but 443 on the inside and 443 on the reverse proxy
      - "2022:2022" # SFTP port
    tty: true
    environment:
      TZ: "America/Los_Angeles"
      # For ease of setup, this is going to use root user.
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: root
    volumes: # Mapping things to elytra, but source directories will remain same as before
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - wings-config:/etc/elytra
      - /var/lib/pterodactyl:/var/lib/pterodactyl # Some things still refer to /var/lib/pterodactyl...
      - /var/lib/pterodactyl:/var/lib/elytra
      - wings-logs:/var/log/elytra
      - /tmp/pterodactyl:/tmp/elytra
  nginx:
    image: ghcr.io/anarchobooleanism/saphnet-nginx:v0.1.0
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    volumes:
      # Main conf file
      - ./reverse-proxy/proxies-docker-host-pve4.conf:/etc/nginx/proxies.conf:ro
      # Certificate files
      - certbot-conf:/etc/letsencrypt:ro
    environment:
      - TZ=${TZ}
    networks:
      - pterodactyl_wing_internal
  certbot:
    image: ghcr.io/anarchobooleanism/certbot-dns-namecheap:v1.0.0-certbotv5.2.2-1
    restart: unless-stopped
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ./certbot-entrypoint.sh:/certbot-entrypoint.sh:ro
    environment:
      TZ: ${TZ}
      DNS_NAMECHEAP_USERNAME: ${DNS_NAMECHEAP_USERNAME}
      DNS_NAMECHEAP_API_KEY: ${DNS_NAMECHEAP_API_KEY}
      CERTBOT_DOMAIN: *instance-domain
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /etc/letsencrypt/live/pterodactyl-node-main.int-net.saphnet.xyz/fullchain.pem ]"]
      interval: 20s
      retries: 12
      start_period: 10s
      timeout: 10s
    # Make sure certbot is run first if not yet, then renew certificates every 12 hours
    entrypoint: [ "/certbot-entrypoint.sh" ]

volumes:
  wings-config:
  wings-logs:
  certbot-conf:

# This is Wings' Network. We don't need much depth here, all you need to know, is
# that it allows the passthrough of the ports from Wings.
networks:
  pterodactyl_wing_internal:
  ptero0:
    name: ptero0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ptero0