# Configuration for Pterodactyl wings, to be paired with the panel
# This is intended to be used on docker-host-pve4, though it still relies on the reverse proxy

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node
#                         https://dev.to/marrouchi/the-challenge-about-ssl-in-docker-containers-no-one-talks-about-32gh

# Be sure to define
# - DNS_NAMECHEAP_USERNAME
# - DNS_NAMECHEAP_API_KEY
# - CERTBOT_EMAIL

x-common:
  INSTANCE_DOMAIN: &instance-domain "pterodactyl-node-main.int-net.saphnet.xyz"

services:
  wing: # TODO: Create automatic backup script
    container_name: pterodactyl-wing # Refer to the panel container this way
    image: ghcr.io/pterodactyl/wings:v1.11.13
    restart: unless-stopped
    networks:
      - ptero0
      - pterodactyl_wing_internal
    ports:
      # - "8443:443" # Is port 8443 on this IP, but 443 on the inside and 443 on the reverse proxy
      - "2022:2022" # SFTP port
    tty: true
    environment:
      TZ: "America/Los_Angeles"
      # For ease of setup, this is going to use root user.
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - wings-config:/etc/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - wings-logs:/var/log/pterodactyl
      - /tmp/pterodactyl:/tmp/pterodactyl
  nginx:
    image: nginx:1.29.3
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    volumes:
      # Main conf file
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/proxies-docker-host-pve4.conf:/etc/nginx/proxies.conf:ro
      # conf.d files
      - ./reverse-proxy/conf.d/block-explots.conf:/etc/nginx/conf.d/block-exploits.conf:ro
      - ./reverse-proxy/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./reverse-proxy/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./reverse-proxy/conf.d/ip-ranges.conf:/etc/nginx/conf.d/ip-ranges.conf:ro
      # Certificate files
      - certbot-conf:/etc/letsencrypt:ro
      # Script to autoreload Nginx when certs are renewed
      - ./reverse-proxy/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh:ro
    environment:
      - TZ=${TZ}
    networks:
      - pterodactyl_wing_internal
    # Nginx fails trying to create these directories for some reason, so we just do it ourselves here
    entrypoint: |
      /bin/sh -c 'mkdir -p /var/cache/nginx/client_temp /var/lib/nginx/cache/public /var/lib/nginx/cache/private && exec /docker-entrypoint.sh nginx -g "daemon off;"'
  certbot:
    image: ghcr.io/anarchobooleanism/certbot-dns-namecheap:v1.0.0-certbotv5.1.0-3
    restart: unless-stopped
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ./certbot-entrypoint.sh:/certbot-entrypoint.sh:ro
    environment:
      TZ: ${TZ}
      DNS_NAMECHEAP_USERNAME: ${DNS_NAMECHEAP_USERNAME}
      DNS_NAMECHEAP_API_KEY: ${DNS_NAMECHEAP_API_KEY}
      CERTBOT_DOMAIN: *instance-domain
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /etc/letsencrypt/live/$CERTBOT_DOMAIN/fullchain.pem ]"]
      interval: 20s
      retries: 12
      start_period: 10s
      timeout: 10s
    # Make sure certbot is run first if not yet, then renew certificates every 12 hours
    entrypoint: [ "/certbot-entrypoint.sh" ]

volumes:
  wings-config:
  wings-logs:
  certbot-conf:

# This is Wings' Network. We don't need much depth here, all you need to know, is
# that it allows the passthrough of the ports from Wings.
networks:
  pterodactyl_wing_internal:
  ptero0:
    name: ptero0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ptero0