# Configuration for Pterodactyl wings, to be paired with the panel
# This is intended to be used on docker-host-pve4

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node
#                         https://dev.to/marrouchi/the-challenge-about-ssl-in-docker-containers-no-one-talks-about-32gh

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  # INSTANCE_DOMAIN: &instance-domain "pterodactyl-node-main.int-net.saphnet.xyz"

services:
  wing:
    image: ghcr.io/pyrohost/elytra:latest@sha256:004c2826224f57f558b19703a0bbfc0a3b38a1991f3aba1e67b841739c9cc959
    container_name: pterodactyl-wing # Refer to the panel container this way
    ports:
      # - "8443:443" # Is port 8443 on this IP, but 443 on the inside and 443 on the reverse proxy
      - "2022:2022" # SFTP port
    tty: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.pterodactyl-wing.rule: Host(`pterodactyl-node-main.int-net.saphnet.xyz`)
      traefik.http.routers.pterodactyl-wing.entrypoints: websecure
      traefik.http.routers.pterodactyl-wing.tls: "true"
      traefik.http.routers.pterodactyl-wing.tls.certresolver: letsencrypt
      traefik.http.routers.pterodactyl-wing.tls.domains[0].main: pterodactyl-node-main.int-net.saphnet.xyz
      traefik.http.routers.pterodactyl-wing.service: pterodactyl-wing-svc
      traefik.http.services.pterodactyl-wing-svc.loadBalancer.server.port: "443"
    environment:
      TZ: *timezone
      # For ease of setup, this is going to use root user.
      WINGS_UID: "0"
      WINGS_GID: "0"
      WINGS_USERNAME: root
    volumes: # Mapping things to elytra, but source directories will remain same as before
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - wings-config:/etc/elytra
      - /var/lib/pterodactyl:/var/lib/pterodactyl # Some things still refer to /var/lib/pterodactyl...
      - /var/lib/pterodactyl:/var/lib/elytra
      - wings-logs:/var/log/elytra
      - /tmp/pterodactyl:/tmp/elytra
    networks:
      - ptero0
      - web_bridge
    restart: unless-stopped

volumes:
  wings-config:
  wings-logs:

# This is Wings' Network. We don't need much depth here, all you need to know, is
# that it allows the passthrough of the ports from Wings.
networks:
  web_bridge:
    name: web_bridge
    external: true
  ptero0:
    name: ptero0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ptero0
