## Stacks

# docker-proxy
[[stack]]
name = "docker-proxy-control"
description = "Used as a way to access the internal Docker socket from outside (read-only), mostly by Homepage."
tags = ["docker-proxy", "iac"]
[stack.config]
server = "control-server"
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-proxy"

# docker-volume-rclone
[[stack]]
name = "docker-volume-rclone-control"
description = "A solution for regularly cloning Docker volumes to a remote NFS location."
tags = ["docker-volume-rclone", "iac"]
[stack.config]
server = "control-server"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
linked_repo = "saphnet-compose-configs"
run_directory = "stacks/docker-volume-rclone"
file_paths = [
  "compose.base.yaml",
  "compose.control-server.yaml"
]

