# Environment variables to set:
# - TAILSCALE_IP, if you want to restrict access to certain ports to just Tailscale only (for external Traefik)

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  NAS_NFS_DRIVER_OPTS: &nas_nfs_driver_opts
    type: "nfs"
    o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
    # Set device here, e.g. ":/mnt/saphnet-nas1b/media-server/deluge/torrent_downloads"
  certificate_groups:
    MEDIA_DOMAINS_MAIN: &media_domains_main "media.int.saphnet.xyz"
    MEDIA_DOMAINS_SANS: &media_domains_sans "*.media.int.saphnet.xyz"

x-services: # Base instances of services to customize
  radarr: &radarr # For movies
    image: ghcr.io/linuxserver/radarr:6.3.0@sha256:e35056574cdc695a9ee745aa1ecda9eab3842450bf4b7b8471b023790fa3861d
    # Set a unique container_name here
    # For volumes, have volume mounted to /config, volume mounted to media folder (e.g. /movies),
    # and volume mounted to /downloads (for Deluge downloads)
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For ports, link host port to container port's 7878
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
  
  sonarr: &sonarr # For shows
    image: ghcr.io/linuxserver/sonarr:4.0.19@sha256:24acea2956a0ccb11f103877d9f4f8576600fb34bff34820ed749c2256dab89f
    # Set a unique container_name here
    # For volumes, have volume mounted to /config, volume mounted to media folder (e.g. /tv),
    # and volume mounted to /downloads (for Deluge downloads)
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For ports, link host port to container port's 8989
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
  
  bazarr: &bazarr # For subtitles
    image: ghcr.io/linuxserver/bazarr:1.6.0@sha256:ab401a0f361cfad328e444838b13d5b334b189d0f556fc91a3623eb581df36df
    # Set a unique container_name here
    # For volumes, have volume mounted to /config, volume mounted to /movies, and volume
    # mounted to /tv
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For ports, link host port to container port's 6767
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped

services:
  jellyfin: # Media streaming
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db # To only update intentionally
    container_name: jellyfin
    volumes:
      - jellyfin-config:/config # Also, self-signed cert files in here
      - jellyfin-cache:/cache
      - media-server-movies:/media/movies
      - media-server-tv:/media/tv
      - media-server-anime:/media/anime
      - media-server-anime-movies:/media/anime-movies
    environment:
      # Optional - alternative address used for autodiscovery
      JELLYFIN_PublishedServerUrl: https://jellyfin.media.int.saphnet.xyz
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:8096:8096"
      - "${TAILSCALE_IP:-0.0.0.0}:8920:8920"
      - "1900:1900"
      - "7359:7359"
    networks:
      - media-server
      - web_bridge
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.media.int.saphnet.xyz`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: letsencrypt
      traefik.http.routers.jellyfin.tls.domains[0].main: *media_domains_main
      traefik.http.routers.jellyfin.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.jellyfin.service: jellyfin-svc

      # Redirect media.int.saphnet.xyz to jellyfin.media.int.saphnet.xyz
      traefik.http.routers.media.rule: "Host(`media.int.saphnet.xyz`)"
      traefik.http.routers.media.middlewares: "media-redirectregex"
      traefik.http.routers.media.tls: "true"
      traefik.http.routers.media.tls.certresolver: letsencrypt
      traefik.http.routers.media.tls.domains[0].main: *media_domains_main
      traefik.http.routers.media.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.media.service: jellyfin-svc
      traefik.http.middlewares.media-redirectregex.redirectregex.regex: "^https://media\\.int\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.media-redirectregex.redirectregex.replacement: "https://jellyfin.media.int.saphnet.xyz/$${1}"
      
      # Many of these come from https://jellyfin.org/docs/general/post-install/networking/reverse-proxy/traefik/
      ## Middleware
      traefik.http.routers.jellyfin.middlewares: jellyfin-mw
      #### The customResponseHeaders option lists the Header names and values to apply to the response.
      traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      #### The stsSeconds is the max-age of the Strict-Transport-Security header. If set to 0, would NOT include the header.
      traefik.http.middlewares.jellyfin-mw.headers.STSSeconds: "315360000"
      #### The stsIncludeSubdomains is set to true, the includeSubDomains directive will be
      #### appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains: "true"
      #### Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSPreload: "true"
      #### Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.
      traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader: "true"
      #### Set frameDeny to true to add the X-Frame-Options header with the value of DENY.
      traefik.http.middlewares.jellyfin-mw.headers.frameDeny: "true"
      #### Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.
      traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff: "true"
      #### Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
      traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION: "1"
      #### The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This
      #### overrides the FrameDeny option.
      traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue: "'allow-from https://jellyfin.media.int.saphnet.xyz'"
      ## HTTP Service
      traefik.http.services.jellyfin-svc.loadBalancer.server.port: "8096"
    devices:
      - /dev/dri:/dev/dri

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.4.0@sha256:d206d9e4056bb90178297df58047791196e7721e6dc19384579b0530702fe086 # To only update intentionally
    container_name: seerr
    volumes:
      - seerr-config:/app/config
    environment:
      LOG_LEVEL: debug
      TZ: *timezone
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:5055:5055"
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: "20s"
      timeout: "3s"
      interval: "15s"
      retries: 3
    labels:
      traefik.enable: "true"
      traefik.http.routers.seerr.rule: Host(`seerr.media.int.saphnet.xyz`)
      traefik.http.routers.seerr.entrypoints: websecure
      traefik.http.routers.seerr.tls: "true"
      traefik.http.routers.seerr.tls.certresolver: letsencrypt
      traefik.http.routers.seerr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.seerr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.seerr.service: seerr-svc
      traefik.http.services.seerr-svc.loadBalancer.server.port: "5055"

      # Redirect jellyseerr to seerr
      traefik.http.routers.jellyseerr.rule: "Host(`jellyseerr.media.int.saphnet.xyz`)"
      traefik.http.routers.jellyseerr.middlewares: "jellyseerr-redirectregex"
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.routers.jellyseerr.tls.certresolver: letsencrypt
      traefik.http.routers.jellyseerr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.jellyseerr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.jellyseerr.service: seerr-svc
      traefik.http.middlewares.jellyseerr-redirectregex.redirectregex.regex: "^https://jellyseerr\\.media\\.int\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.jellyseerr-redirectregex.redirectregex.replacement: "https://seerr.media.int.saphnet.xyz/$${1}"
    init: true

  flaresolverr: # Handles CloudFlare prompts for Prowlarr
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    container_name: flaresolverr
    volumes:
      - flaresolverr-config:/config
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      LOG_FILE: "${LOG_FILE:-none}"
      LOG_HTML: "${LOG_HTML:-false}"
      CAPTCHA_SOLVER: "${CAPTCHA_SOLVER:-none}"
      TZ: *timezone
    # ports:
    #   - "8191:8191"
    networks:
      - media-server
    restart: unless-stopped
  
  prowlarr: # Handles trackers
    image: ghcr.io/linuxserver/prowlarr:2.5.2@sha256:2f3d31307beba3ba2dd226d191f5f5c14ee3b4d8b49277c64683f5ed97083179
    container_name: prowlarr
    volumes:
      - prowlarr-config:/config
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # ports:
    #   - "9696:9696"
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.media.int.saphnet.xyz`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.routers.prowlarr.tls.certresolver: letsencrypt
      traefik.http.routers.prowlarr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.prowlarr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.prowlarr.service: prowlarr-svc
      traefik.http.services.prowlarr-svc.loadBalancer.server.port: "9696"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8.7.0@sha256:2d6107f758d882a59fe9d646aa54fa8a5a4fb7a40995125fade575652a3f7871
    container_name: recyclarr
    volumes:
      - recyclarr-config:/config
    environment:
      TZ: *timezone
      RECYCLARR_CREATE_CONFIG: "true"
    networks:
      - media-server
    restart: unless-stopped
    user: "1000:1000"
    
  radarr: # For movies
    container_name: radarr
    volumes:
      - radarr-config:/config
      - media-server-movies:/movies # Jellyfin movies folder
      - seedbox-torrent-downloads:/downloads # Deluge complete downloads folder
    # ports:
    #   - "7878:7878"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: Host(`radarr.media.int.saphnet.xyz`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: "true"
      traefik.http.routers.radarr.tls.certresolver: letsencrypt
      traefik.http.routers.radarr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.radarr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.radarr.service: radarr-svc
      traefik.http.services.radarr-svc.loadBalancer.server.port: "7878"
    <<: *radarr
  
  radarr-anime: # For anime movies
    container_name: radarr-anime
    volumes:
      - radarr-anime-config:/config
      - media-server-anime-movies:/anime-movies # Jellyfin movies folder
      - seedbox-torrent-downloads:/downloads # Deluge complete downloads folder
    # ports:
    #   - "7879:7878"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr-anime.rule: Host(`radarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.radarr-anime.entrypoints: websecure
      traefik.http.routers.radarr-anime.tls: "true"
      traefik.http.routers.radarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.radarr-anime.tls.domains[0].main: *media_domains_main
      traefik.http.routers.radarr-anime.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.radarr-anime.service: radarr-anime-svc
      traefik.http.services.radarr-anime-svc.loadBalancer.server.port: "7878"
    <<: *radarr

  sonarr: # For shows
    container_name: sonarr
    volumes:
      - sonarr-config:/config
      - media-server-tv:/tv
      - seedbox-torrent-downloads:/downloads
    # ports:
    #   - "8989:8989"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: Host(`sonarr.media.int.saphnet.xyz`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.routers.sonarr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.sonarr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.sonarr.service: sonarr-svc
      traefik.http.services.sonarr-svc.loadBalancer.server.port: "8989"
    <<: *sonarr
  
  sonarr-anime: # For anime
    container_name: sonarr-anime
    volumes:
      - sonarr-anime-config:/config
      - media-server-anime:/anime
      - seedbox-torrent-downloads:/downloads
    # ports:
    #   - "8990:8989"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr-anime.rule: Host(`sonarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.sonarr-anime.entrypoints: websecure
      traefik.http.routers.sonarr-anime.tls: "true"
      traefik.http.routers.sonarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.sonarr-anime.tls.domains[0].main: *media_domains_main
      traefik.http.routers.sonarr-anime.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.sonarr-anime.service: sonarr-anime-svc
      traefik.http.services.sonarr-anime-svc.loadBalancer.server.port: "8989"
    <<: *sonarr
  
  bazarr: # For subtitles
    container_name: bazarr
    volumes:
      - bazarr-config:/config
      - media-server-movies:/movies
      - media-server-tv:/tv
    # ports:
    #   - "6767:6767"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr.rule: Host(`bazarr.media.int.saphnet.xyz`)
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr.tls.certresolver: letsencrypt
      traefik.http.routers.bazarr.tls.domains[0].main: *media_domains_main
      traefik.http.routers.bazarr.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.bazarr.service: bazarr-svc
      traefik.http.services.bazarr-svc.loadBalancer.server.port: "6767"
    <<: *bazarr
  
  bazarr-anime: # For anime subtitles
    container_name: bazarr-anime
    volumes:
      - bazarr-anime-config:/config
      - media-server-anime-movies:/anime-movies
      - media-server-anime:/anime
    # ports:
    #   - "6768:6767"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr-anime.rule: Host(`bazarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.bazarr-anime.entrypoints: websecure
      traefik.http.routers.bazarr-anime.tls: "true"
      traefik.http.routers.bazarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.bazarr-anime.tls.domains[0].main: *media_domains_main
      traefik.http.routers.bazarr-anime.tls.domains[0].sans: *media_domains_sans
      traefik.http.routers.bazarr-anime.service: bazarr-anime-svc
      traefik.http.services.bazarr-anime-svc.loadBalancer.server.port: "6767"
    <<: *bazarr

networks:
  media-server: # Should be externally available
    name: media-server
  web_bridge:
    name: web_bridge
    external: true

volumes:
  seedbox-files:
  jellyfin-config:
  jellyfin-cache:
  seerr-config:
  flaresolverr-config:
  prowlarr-config:
  recyclarr-config:
  radarr-config:
  radarr-anime-config:
  sonarr-config:
  sonarr-anime-config:
  bazarr-config:
  bazarr-anime-config:
  media-server-movies:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/movies"
  media-server-tv:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/tv"
  media-server-anime:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/anime"
  media-server-anime-movies:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/anime-movies"
  seedbox-torrent-files:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_files"
  seedbox-torrent-downloads:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_downloads"
