# To be run, and merged, with another host-specific file (e.g. docker-host-pve3.yaml)
# Example command:
# docker compose -f base.yaml -f docker-host-pve3.yaml up

# Environment variables to set:
# - NAMECHEAP_API_USER
# - NAMECHEAP_API_KEY
# - ACME_EMAIL

services:
  traefik: # Reverse proxy, with dashboard enabled
    image: traefik:v3.6@sha256:a9890c898f379c1905ee5b28342f6b408dc863f08db2dab20e46c267d1ff463a
    container_name: traefik
    command:
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=172.16.0.0/12,10.0.0.0/8"
      - "--entrypoints.websecure.proxyProtocol.trustedIPs=172.16.0.0/12,10.0.0.0/8"
      # For Immich
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=600s"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web_bridge" # Make sure this is the name of your Docker network!

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

      # SSL certificates
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=namecheap"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      # For backend services
      - "--serversTransport.insecureSkipVerify=true"

      # Miscellaneous
      - "--global.sendAnonymousUsage=true"
    ports: # Port 8080 is for dashboard, but it should be through HTTPS anyway
      - "80:80"
      - "443:443"
    environment:
      NAMECHEAP_API_USER: "${NAMECHEAP_API_USER}"
      NAMECHEAP_API_KEY: "${NAMECHEAP_API_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - web_bridge
    extra_hosts: # To connect to containers with network_mode as "host"
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  traefik-certs:

networks:
  web_bridge:
    name: web_bridge
    attachable: true
