# To be run, and merged, with the base file
# Example command:
# docker compose -f base.yaml -f docker-host-pve4.yaml up

# Extra environment variables to set (in addition to in base.yaml):
# - DASHBOARD_LOGIN (create with htpasswd, is in format of username:passwordhash)

x-common:
  DASHBOARD_HOST: &dashboard_host "Host(`docker-host-pve4.int.saphnet.xyz`)" # Domain name for dashboard
  certificate_groups:
    HOST_INT_DOMAINS_MAIN: &host_int_domains_main "docker-host-pve4.int.saphnet.xyz"
    HOST_INT_DOMAINS_SANS: &host_int_domains_sans "*.docker-host-pve4.int.saphnet.xyz"

services:
  traefik:
    labels:
      # Enable self‑routing
      traefik.enable: "true"

      # Dashboard router
      traefik.http.routers.dashboard.rule: *dashboard_host
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls: "true"
      traefik.http.routers.dashboard.tls.certresolver: letsencrypt
      traefik.http.routers.dashboard.tls.domains[0].main: *host_int_domains_main
      traefik.http.routers.dashboard.tls.domains[0].sans: *host_int_domains_sans

      # Basic‑auth middleware
      traefik.http.middlewares.dashboard-auth.basicauth.users: "${DASHBOARD_LOGIN}"
      traefik.http.routers.dashboard.middlewares: dashboard-auth@docker
