# Extra environment variables to set (in addition to in base.yaml):
# - ED25519_PRIVATE_KEY_HEX (create with "openssl rand -hex 32")
# - DASHBOARD_LOGIN (create with htpasswd, is in format of username:passwordhash)

x-common:
  DASHBOARD_HOST: &dashboard_host "Host(`traefik-vps1.saphnet.xyz`)" # Domain name for dashboard
  ANUBIS: &anubis-environment # Default bind is 8923
    DIFFICULTY: "4"
    ED25519_PRIVATE_KEY_HEX: "${ED25519_PRIVATE_KEY_HEX}"
    OG_PASSTHROUGH: "true"
    WEBMASTER_EMAIL: "homelab@saphnet.xyz"
    TARGET: " " # This is HIGHLY important!!!! Prevents redirect loops (do NOT remove)
  certificate_groups:
    THEVOIDPACT_DOMAINS_MAIN: &thevoidpact_domains_main "map.thevoidpact.xyz"
    THEVOIDPACT_DOMAINS_SANS: &thevoidpact_domains_sans "anubis.thevoidpact.xyz"
    SAPHNET_DOMAINS_MAIN: &saphnet_domains_main "saphnet.xyz"
    SAPHNET_DOMAINS_SANS: &saphnet_domains_sans "www.saphnet.xyz,anubis.saphnet.xyz,immich.saphnet.xyz"
    SAPHNET_MEDIA_DOMAINS_MAIN: &saphnet_media_domains_main "media.saphnet.xyz"
    SAPHNET_MEDIA_DOMAINS_SANS: &saphnet_media_domains_sans "*.media.saphnet.xyz"

x-services:
  anubis: &anubis
    image: ghcr.io/techarohq/anubis:latest@sha256:4bdf6ddd1a8dc8bfe7a33d823a1cb72157885ca4fd3ee749654b21cba732e439
    # Set container_name here
    # For environment, set COOKIE_DOMAIN, PUBLIC_URL, and REDIRECT_DOMAINS,
    # and import anubis-environment!
    # Make sure to set the right labels for your Anubis instance!
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: "5s"
      timeout: "30s"
      retries: 5
      start_period: "500ms"
    networks:
      - web_bridge
    restart: unless-stopped

services:
  traefik:
    labels:
      # Enable self‑routing
      traefik.enable: "true"

      # Dashboard router
      # Can be accessed via https://traefik-vps1.saphnet.xyz, Tailscale only
      traefik.http.routers.dashboard.rule: *dashboard_host
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls: "true"
      traefik.http.routers.dashboard.tls.certresolver: letsencrypt
      traefik.http.routers.dashboard.middlewares: dashboard-ipallowlist, dashboard-auth
      traefik.http.middlewares.dashboard-auth.basicauth.users: "${DASHBOARD_LOGIN}" # Leave only accessible via Tailscale
      # Interestingly, this won't work if we don't add Docker subnet ranges
      traefik.http.middlewares.dashboard-ipallowlist.ipallowlist.sourcerange: "100.64.0.0/10, fd7a:115c:a1e0::/48, 172.16.0.0/12, 10.0.0.0/8"

      # Anubis middleware
      traefik.http.middlewares.anubis-thevoidpact.forwardauth.address: http://anubis-thevoidpact:8923/.within.website/x/cmd/anubis/api/check
      traefik.http.middlewares.anubis-saphnet.forwardauth.address: http://anubis-saphnet:8923/.within.website/x/cmd/anubis/api/check
      
      # immich.saphnet.xyz
      traefik.http.routers.immich.rule: Host(`immich.saphnet.xyz`)
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.tls: "true"
      traefik.http.routers.immich.tls.certresolver: letsencrypt
      traefik.http.routers.immich.tls.domains[0].main: *saphnet_domains_main
      traefik.http.routers.immich.tls.domains[0].sans: *saphnet_domains_sans
      traefik.http.routers.immich.middlewares: anubis-saphnet@docker
      traefik.http.routers.immich.service: immich-svc
      traefik.http.services.immich-svc.loadbalancer.server.url: http://docker-host-pve3:2283

      # map.thevoidpact.xyz
      traefik.http.routers.thevoidpact-map.rule: Host(`map.thevoidpact.xyz`)
      traefik.http.routers.thevoidpact-map.entrypoints: websecure
      traefik.http.routers.thevoidpact-map.tls: "true"
      traefik.http.routers.thevoidpact-map.tls.certresolver: letsencrypt
      traefik.http.routers.thevoidpact-map.tls.domains[0].main: *thevoidpact_domains_main
      traefik.http.routers.thevoidpact-map.tls.domains[0].sans: *thevoidpact_domains_sans
      traefik.http.routers.thevoidpact-map.middlewares: anubis-thevoidpact@docker, thevoidpact-map-cache
      traefik.http.routers.thevoidpact-map.service: thevoidpact-map-svc
      traefik.http.middlewares.thevoidpact-map-cache.plugin.cache.path: /tmp/thevoidpact-map-cache
      traefik.http.services.thevoidpact-map-svc.loadbalancer.server.url: http://docker-host-pve4:63624
      # /tiles router
      traefik.http.routers.thevoidpact-map-tiles.rule: Host(`map.thevoidpact.xyz`) && PathPrefix(`/tiles`)
      traefik.http.routers.thevoidpact-map-tiles.entrypoints: websecure
      traefik.http.routers.thevoidpact-map-tiles.tls: "true"
      traefik.http.routers.thevoidpact-map-tiles.tls.certresolver: letsencrypt
      traefik.http.routers.thevoidpact-map-tiles.tls.domains[0].main: *thevoidpact_domains_main
      traefik.http.routers.thevoidpact-map-tiles.tls.domains[0].sans: *thevoidpact_domains_sans
      traefik.http.routers.thevoidpact-map-tiles.middlewares: anubis-thevoidpact@docker, thevoidpact-map-tiles-cache-header, thevoidpact-map-tiles-cache
      traefik.http.routers.thevoidpact-map-tiles.service: thevoidpact-map-svc
      # Set max-age for tiles to 5 minutes, be consistent with how often Dynmap actually updates tiles
      traefik.http.middlewares.thevoidpact-map-tiles-cache-header.headers.customresponseheaders.Cache-Control: "max-age=300"
      # Cache plugin
      traefik.http.middlewares.thevoidpact-map-tiles-cache.plugin.cache.path: /tmp/thevoidpact-map-tiles-cache

      # Media stack
      # jellyfin.media.saphnet.xyz
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.media.saphnet.xyz`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: letsencrypt
      traefik.http.routers.jellyfin.tls.domains[0].main: *saphnet_media_domains_main
      traefik.http.routers.jellyfin.tls.domains[0].sans: *saphnet_media_domains_sans
      traefik.http.routers.jellyfin.middlewares: anubis-saphnet@docker, jellyfin-mw
      traefik.http.routers.jellyfin.service: jellyfin-svc
      traefik.http.services.jellyfin-svc.loadbalancer.server.url: http://docker-host-pve3:8096
      ## Jellyfin-specific middleware
      #### The customResponseHeaders option lists the Header names and values to apply to the response.
      traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      #### The stsSeconds is the max-age of the Strict-Transport-Security header. If set to 0, would NOT include the header.
      traefik.http.middlewares.jellyfin-mw.headers.STSSeconds: "315360000"
      #### The stsIncludeSubdomains is set to true, the includeSubDomains directive will be
      #### appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains: "true"
      #### Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSPreload: "true"
      #### Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.
      traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader: "true"
      #### Set frameDeny to true to add the X-Frame-Options header with the value of DENY.
      traefik.http.middlewares.jellyfin-mw.headers.frameDeny: "true"
      #### Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.
      traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff: "true"
      #### Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
      traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION: "1"
      #### The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This
      #### overrides the FrameDeny option.
      traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue: "'allow-from https://jellyfin.media.saphnet.xyz'"

      ## Redirect from media.saphnet.xyz
      traefik.http.routers.saphnet-media.rule: "Host(`media.saphnet.xyz`)"
      traefik.http.routers.saphnet-media.middlewares: "saphnet-media-redirectregex"
      traefik.http.routers.saphnet-media.tls: "true"
      traefik.http.routers.saphnet-media.tls.certresolver: letsencrypt
      traefik.http.routers.saphnet-media.tls.domains[0].main: *saphnet_media_domains_main
      traefik.http.routers.saphnet-media.tls.domains[0].sans: *saphnet_media_domains_sans
      traefik.http.routers.saphnet-media.service: jellyfin-svc
      traefik.http.middlewares.saphnet-media-redirectregex.redirectregex.regex: "^https://media\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.saphnet-media-redirectregex.redirectregex.replacement: "https://jellyfin.media.saphnet.xyz/$${1}"

      # jellyseerr.media.saphnet.xyz
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.media.saphnet.xyz`)
      traefik.http.routers.jellyseerr.entrypoints: websecure
      traefik.http.routers.jellyseerr.tls: "true"
      traefik.http.routers.jellyseerr.tls.certresolver: letsencrypt
      traefik.http.routers.jellyseerr.tls.domains[0].main: *saphnet_media_domains_main
      traefik.http.routers.jellyseerr.tls.domains[0].sans: *saphnet_media_domains_sans
      traefik.http.routers.jellyseerr.middlewares: anubis-saphnet@docker
      traefik.http.routers.jellyseerr.service: jellyseerr-svc
      traefik.http.services.jellyseerr-svc.loadbalancer.server.url: http://docker-host-pve3:5055
    volumes:
      - thevoidpact-map-cache:/tmp/thevoidpact-map-tiles-cache
      - thevoidpact-map-cache:/tmp/thevoidpact-map-cache

  under-construction: # Serving "under construction" pages
    image: ghcr.io/palmergw/under-construction-page:latest@sha256:2fd2eab189cb8bef5ba7c1b6bc76f86c46dbbe68644bf1ae99e2b3c1f47389e7
    container_name: under-construction
    labels:
      traefik.enable: "true"
      traefik.http.services.under-construction-svc.loadbalancer.server.port: "80"

      # saphnet.xyz
      traefik.http.routers.saphnet.rule: Host(`saphnet.xyz`)
      traefik.http.routers.saphnet.entrypoints: websecure
      traefik.http.routers.saphnet.tls: "true"
      traefik.http.routers.saphnet.tls.certresolver: letsencrypt
      traefik.http.routers.saphnet.tls.domains[0].main: *saphnet_domains_main
      traefik.http.routers.saphnet.tls.domains[0].sans: *saphnet_domains_sans
      traefik.http.routers.saphnet.middlewares: anubis-saphnet@docker
      traefik.http.routers.saphnet.service: under-construction-svc

      # www.saphnet.xyz
      traefik.http.routers.saphnet-www.rule: "Host(`www.saphnet.xyz`)"
      traefik.http.routers.saphnet-www.middlewares: "saphnet-www-redirectregex"
      traefik.http.routers.saphnet-www.tls: true
      traefik.http.routers.saphnet-www.tls.certresolver: letsencrypt
      traefik.http.routers.saphnet-www.tls.domains[0].main: *saphnet_domains_main
      traefik.http.routers.saphnet-www.tls.domains[0].sans: *saphnet_domains_sans
      traefik.http.routers.saphnet-www.service: under-construction-svc
      traefik.http.middlewares.saphnet-www-redirectregex.redirectregex.regex: "^https://www\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.saphnet-www-redirectregex.redirectregex.replacement: "https://saphnet.xyz/$${1}"
    networks:
      - web_bridge
    restart: unless-stopped

  anubis-thevoidpact:
    <<: *anubis
    container_name: anubis-main
    labels:
      traefik.enable: "true"
      traefik.http.routers.anubis-thevoidpact.rule: Host(`anubis.thevoidpact.xyz`)
      traefik.http.routers.anubis-thevoidpact.entrypoints: websecure
      traefik.http.routers.anubis-thevoidpact.tls: "true"
      traefik.http.routers.anubis-thevoidpact.tls.certresolver: letsencrypt
      traefik.http.routers.anubis-thevoidpact.tls.domains[0].main: *thevoidpact_domains_main
      traefik.http.routers.anubis-thevoidpact.tls.domains[0].sans: *thevoidpact_domains_sans
      traefik.http.routers.anubis-thevoidpact.service: anubis-thevoidpact-svc
      traefik.http.services.anubis-thevoidpact-svc.loadbalancer.server.port: "8923"
    environment:
      <<: *anubis-environment
      COOKIE_DOMAIN: "thevoidpact.xyz"
      PUBLIC_URL: "https://anubis.thevoidpact.xyz"
      REDIRECT_DOMAINS: "map.thevoidpact.xyz"

  anubis-saphnet:
    <<: *anubis
    container_name: anubis-saphnet
    labels:
      traefik.enable: "true"
      traefik.http.routers.anubis-saphnet.rule: Host(`anubis.saphnet.xyz`)
      traefik.http.routers.anubis-saphnet.entrypoints: websecure
      traefik.http.routers.anubis-saphnet.tls: "true"
      traefik.http.routers.anubis-saphnet.tls.certresolver: letsencrypt
      traefik.http.routers.anubis-saphnet.tls.domains[0].main: saphnet.xyz
      traefik.http.routers.anubis-saphnet.tls.domains[0].sans: "www.saphnet.xyz,anubis.saphnet.xyz"
      traefik.http.routers.anubis-saphnet.service: anubis-saphnet-svc
      traefik.http.services.anubis-saphnet-svc.loadbalancer.server.port: "8923"
    environment:
      <<: *anubis-environment
      COOKIE_DOMAIN: "saphnet.xyz"
      PUBLIC_URL: "https://anubis.saphnet.xyz"
      REDIRECT_DOMAINS: >-
        jellyfin.media.saphnet.xyz,jellyseerr.media.saphnet.xyz,saphnet.xyz,immich.saphnet.xyz

volumes:
  thevoidpact-map-tiles-cache:
  thevoidpact-map-cache:
