# Be sure to define
# - VELOCITY_FORWARDING_SECRET
# - RCON_PASSWORD # IMPORTANT: Avoid "#" in your password!!
# - SFTP_PASSWORD
# - TAILSCALE_IP
# Note: The actual environment variable, in the Velocity container, should be prefixed with "CFG_"

# Variables you'll want to frequently change
x-common:
  VELOCITY_VERSION: &velocity-version "3.5.0-SNAPSHOT" # See: https://papermc.io/downloads/velocity

services:
  velocity:
    image: itzg/mc-proxy:java21@sha256:e716bba317726491994210990dbb066d4349e6b3704d898207b993153a3f0a77
    container_name: velocity
    volumes:
      - ./velocity-config/velocity.toml:/config/velocity.toml:ro
      - velocity-data:/server
    environment:
      # For secrets
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      VELOCITY_FORWARDING_SECRET: "${VELOCITY_FORWARDING_SECRET}" # We will handle this ourselves
      # Velocity configuration
      TYPE: VELOCITY
      MEMORY: "512m"
      VELOCITY_VERSION: *velocity-version
      VELOCITY_BUILD_ID: latest
      ENABLE_RCON: "true"
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    ports:
      - "25565:25565"
      - "${TAILSCALE_IP:-0.0.0.0}:25575:25575"
    # As mc-proxy can only fill in certain types of files, we will set forwarding.secret ourselves
    # For last command, see: https://github.com/itzg/docker-mc-proxy/blob/master/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        echo -n '${VELOCITY_FORWARDING_SECRET}' > '/config/forwarding.secret'
        exec /usr/bin/run-bungeecord.sh
    restart: unless-stopped
  
  velocity-sftp: 
    image: ghcr.io/anarchobooleanism/saphnet-sftp:v0.1.1@sha256:bb164f405864b029fd3b3e5501bb347de0acd8a54436b3ffc79b9b456e3ce152
    container_name: velocity-sftp
    volumes:
      - velocity-data:/home/velocity-user/sftp
      - sftp-ssh-data:/etc/ssh # For persistence of keys
    environment:
      SFTP_USERNAME: velocity-user
      SFTP_PASSWORD: "${SFTP_PASSWORD}"
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:2022:22"
    restart: unless-stopped

volumes:
  velocity-data:
  sftp-ssh-data:
