services:
  # Be sure to run docker-proxy on the same host! Should be accessible via "docker-proxy"

  # This expects to be given a path to a secrets file (by the "docker compose up" command)
  # to use for secrets as environment variables
  homepage:
    image: ghcr.io/anarchobooleanism/saphnet-homepage:edge@sha256:48f38f4e197ad89cd40f1aeb6dabdbf48ac8227fd7dc730b6feb285e2965fe5d
    container_name: homepage
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.int.saphnet.xyz
    env_file:
      - ./.env
      - ${SOPS_SECRETS_PATH:?Please set SOPS_SECRETS_PATH}
    # ports:
    # - "3000:3000"
    networks:
      - web_bridge
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: Host(`homepage.int.saphnet.xyz`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.tls.certresolver: letsencrypt
      traefik.http.routers.homepage.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.homepage.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.homepage.service: homepage-svc
      traefik.http.services.homepage-svc.loadBalancer.server.port: "3000"
      # Redirect int.saphnet.xyz to homepage.int.saphnet.xyz
      traefik.http.routers.saphnet-int.rule: "Host(`int.saphnet.xyz`)"
      traefik.http.routers.saphnet-int.middlewares: "saphnet-int-redirectregex"
      traefik.http.routers.saphnet-int.tls: "true"
      traefik.http.routers.saphnet-int.tls.certresolver: letsencrypt
      traefik.http.routers.saphnet-int.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.saphnet-int.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.saphnet-int.service: homepage-svc
      traefik.http.middlewares.saphnet-int-redirectregex.redirectregex.regex: "^https://int\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.saphnet-int-redirectregex.redirectregex.replacement: "https://homepage.int.saphnet.xyz/$${1}"

networks:
  web_bridge:
    name: web_bridge
    external: true
