# Configuration for Pterodactyl panel, to be combined with wings
# This is intended to be used with nginx-proxy-manager, on docker-host-nginx

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node

# Common variables, declared here
x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "basic_mysql_password"
    MYSQL_ROOT_PASSWORD: "basic_mysql_root_password"
  panel:
    &panel-environment
    #This is the URL that your panel will be on after being reverse proxied.
    # set this to "https://yoursubdomain.yourdomain.yourdomainstld"
    APP_URL: "https://pterodactyl.int.saphnet.xyz"
    # A list of valid timezones can be found here:
    # http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "America/Los_Angeles"
    APP_SERVICE_AUTHOR: "homelab@saphnet.xyz"
    TRUSTED_PROXIES: "nginx-proxy-manager"
  mail:
    &mail-environment
    MAIL_FROM: "homelab@saphnet.xyz"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail.privateemail.com"
    MAIL_PORT: "465"
    MAIL_USERNAME: "homelab@saphnet.xyz"
    MAIL_PASSWORD: ${MAIL_PASSWORD}
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:12.1.2
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database-data:/var/lib/mysql
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - pterodactyl_panel_internal
  cache:
    image: redis:8.4.0-alpine
    restart: unless-stopped
    networks:
      - pterodactyl_panel_internal
  panel:
    container_name: pterodactyl-panel # Refer to the panel container this way
    image: ghcr.io/pterodactyl/panel:v1.11.11
    restart: unless-stopped
    # ports:
    #   - "802:80" # Web port
    volumes:
      - panel-data:/app/var/
      - panel-logs:/app/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    networks:
      - web_bridge
      - pterodactyl_panel_internal

volumes:
  database-data:
  panel-data:
  panel-logs:

networks:
  pterodactyl_panel_internal:
  web_bridge:
    name: web_bridge