# Configuration for Pterodactyl panel, to be combined with wings
# This is intended to be used on docker-host-core

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node

# Environment variables to set:
# - MAIL_PASSWORD
# - RUSTIC_S3_REGION
# - RUSTIC_S3_ACCESS_KEY_ID
# - RUSTIC_S3_SECRET_ACCESS_KEY
# - RUSTIC_S3_BUCKET
# - RUSTIC_S3_ENDPOINT (include "https://"!)
# - HASHIDS_SALT (should be 20 characters, to generate this, run "head -c20 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9/.' | head -c20")

# Common variables, declared here
x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  database: &db-environment
    MYSQL_PASSWORD: &db-password "basic_mysql_password"
    MYSQL_ROOT_PASSWORD: "basic_mysql_root_password"
  panel: &panel-environment
    #This is the URL that your panel will be on after being reverse proxied.
    # set this to "https://yoursubdomain.yourdomain.yourdomainstld"
    APP_URL: "https://pterodactyl.int.saphnet.xyz"
    # A list of valid timezones can be found here:
    # http://php.net/manual/en/timezones.php
    APP_TIMEZONE: *timezone
    APP_SERVICE_AUTHOR: "homelab@saphnet.xyz"
    TRUSTED_PROXIES: "traefik"
    HASHIDS_SALT: "${HASHIDS_SALT}"
    HASHIDS_LENGTH: "8"
  mail: &mail-environment
    MAIL_FROM: "homelab@saphnet.xyz"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail.privateemail.com"
    MAIL_PORT: "465"
    MAIL_USERNAME: "homelab@saphnet.xyz"
    MAIL_PASSWORD: "${MAIL_PASSWORD}"
    MAIL_ENCRYPTION: "true"
  # S3-based backup
  backup: &backup-environment
    APP_BACKUP_DRIVER: rustic_s3
    RUSTIC_S3_FORCE_PATH_STYLE: "true"
    RUSTIC_REPOSITORY_BASE_PATH: /var/lib/elytra/rustic-repos # For some reason, the default is /var/lib/pterodactyl...
    RUSTIC_S3_REGION: "${RUSTIC_S3_REGION}"
    RUSTIC_S3_ACCESS_KEY_ID: "${RUSTIC_S3_ACCESS_KEY_ID}"
    RUSTIC_S3_SECRET_ACCESS_KEY: "${RUSTIC_S3_SECRET_ACCESS_KEY}"
    RUSTIC_S3_BUCKET: "${RUSTIC_S3_BUCKET}"
    RUSTIC_S3_ENDPOINT: "${RUSTIC_S3_ENDPOINT}"

services:
  database:
    image: mariadb:12@sha256:e0236fc6386e7eacd9359e59d0a078bd7aa0d18280d36d13061121bedeaee903
    command: --default-authentication-plugin=mysql_native_password
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - pterodactyl_panel_internal
    restart: unless-stopped
  
  cache:
    image: redis:8@sha256:125f446fbd4c4345cdbd0f60c61ed83c35a10e09436dd797e0e82377325034f5
    networks:
      - pterodactyl_panel_internal
    restart: unless-stopped
  
  panel:
    image: ghcr.io/pyrodactyl-oss/pyrodactyl:latest@sha256:8d7c2d08bf8146bda2b5bfb3627d9ccef95d1e1a01c3efd3ac4a7572ff1595c8
    container_name: pterodactyl-panel # Refer to the panel container this way
    # ports:
    #   - "802:80" # Web port
    labels:
      traefik.enable: "true"
      traefik.http.routers.pterodactyl.rule: Host(`pterodactyl.int.saphnet.xyz`)
      traefik.http.routers.pterodactyl.entrypoints: websecure
      traefik.http.routers.pterodactyl.tls: "true"
      traefik.http.routers.pterodactyl.tls.certresolver: letsencrypt
      traefik.http.routers.pterodactyl.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.pterodactyl.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.routers.pterodactyl.service: pterodactyl-svc
      traefik.http.services.pterodactyl-svc.loadBalancer.server.port: "80"
    environment:
      <<: [*panel-environment, *mail-environment, *backup-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    volumes:
      - panel-data:/app/var/
      - panel-logs:/app/storage/logs
    networks:
      - web_bridge
      - pterodactyl_panel_internal
    restart: unless-stopped

volumes:
  database-data:
  panel-data:
  panel-logs:

networks:
  pterodactyl_panel_internal:
  web_bridge:
    name: web_bridge
    external: true
