x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  jellyfin: # Media streaming
    image: jellyfin/jellyfin:10.11.5
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900
      - 7359:7359
    volumes:
      - jellyfin-config:/config # Also, self-signed cert files in here
      - jellyfin-cache:/cache
      - media-server-movies:/media/movies
      - media-server-tv:/media/tv
      - media-server-anime:/media/anime
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.int.saphnet.xyz
    devices:
      - /dev/dri:/dev/dri
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  flaresolverr: # Handles CloudFlare prompts for Prowlarr
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FILE: ${LOG_FILE:-none}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: *timezone
    ports:
      - 8191:8191
    volumes:
      - flaresolverr-config:/config
    restart: unless-stopped
  
  prowlarr: # Handles trackers
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: *timezone
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
  radarr: # For movies
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: *timezone
    volumes:
      - radarr-config:/config
      - media-server-movies:/movies # Jellyfin movies folder
      - seedbox-torrent-downloads:/downloads # Deluge complete downloads folder
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: # For shows
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: *timezone
    volumes:
      - sonarr-config:/config
      - media-server-tv:/tv
      - seedbox-torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  sonarr-anime: # For anime
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr-anime
    environment:
      PUID: 1000
      PGID: 1000
      TZ: *timezone
    volumes:
      - sonarr-anime-config:/config
      - media-server-anime:/anime
      - seedbox-torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  bazarr: # For subtitles
    image: lscr.io/linuxserver/bazarr:1.5.4
    container_name: bazarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: *timezone
    volumes:
      - bazarr-config:/config
      - media-server-movies:/movies
      - media-server-tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  seedbox-files:
  jellyfin-config:
  jellyfin-cache:
  flaresolverr-config:
  prowlarr-config:
  radarr-config:
  sonarr-config:
  sonarr-anime-config:
  bazarr-config:
  media-server-movies:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/movies"
  media-server-tv:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/tv"
  media-server-anime:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/anime"
  seedbox-torrent-files:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_files"
  seedbox-torrent-downloads:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_downloads"