# Environment variables to set:
# - TAILSCALE_IP, if you want to restrict access to certain ports to just Tailscale only (for external Traefik)

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  NAS_NFS_DRIVER_OPTS: &nas_nfs_driver_opts
    type: "nfs"
    o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
    # Set device here, e.g. ":/mnt/saphnet-nas1b/media-server/deluge/torrent_downloads"

x-services: # Base instances of services to customize
  radarr: &radarr # For movies
    image: lscr.io/linuxserver/radarr:6.0.4
    # Set a unique container_name here
    # For ports, link host port to container port's 7878
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For volumes, have volume mounted to /config, volume mounted to media folder (e.g. /movies),
    # and volume mounted to /downloads (for Deluge downloads)
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
  
  sonarr: &sonarr # For shows
    image: lscr.io/linuxserver/sonarr:4.0.16
    # Set a unique container_name here
    # For ports, link host port to container port's 8989
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For volumes, have volume mounted to /config, volume mounted to media folder (e.g. /tv),
    # and volume mounted to /downloads (for Deluge downloads)
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped
  
  bazarr: &bazarr # For subtitles
    image: lscr.io/linuxserver/bazarr:1.5.4
    # Set a unique container_name here
    # For ports, link host port to container port's 6767
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    # For volumes, have volume mounted to /config, volume mounted to /movies, and volume
    # mounted to /tv
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped

services:
  jellyfin: # Media streaming
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:8096:8096"
      - "${TAILSCALE_IP:-0.0.0.0}:8920:8920"
      - "1900:1900"
      - "7359:7359"
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.media.int.saphnet.xyz`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.tls.certresolver: letsencrypt
      traefik.http.routers.jellyfin.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.jellyfin.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.jellyfin.service: jellyfin-svc

      # Redirect media.int.saphnet.xyz to jellyfun.media.int.saphnet.xyz
      traefik.http.routers.media.rule: "Host(`media.int.saphnet.xyz`)"
      traefik.http.routers.media.middlewares: "media-redirectregex"
      traefik.http.routers.media.tls: true
      traefik.http.routers.media.tls.certresolver: letsencrypt
      traefik.http.routers.media.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.media.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.media.service: jellyfin-svc
      traefik.http.middlewares.media-redirectregex.redirectregex.regex: "^https://media\\.int\\.saphnet\\.xyz/(.*)"
      traefik.http.middlewares.media-redirectregex.redirectregex.replacement: "https://jellyfin.media.int.saphnet.xyz/$${1}"
      
      # Many of these come from https://jellyfin.org/docs/general/post-install/networking/reverse-proxy/traefik/
      ## Middleware
      traefik.http.routers.jellyfin.middlewares: jellyfin-mw
      #### The customResponseHeaders option lists the Header names and values to apply to the response.
      traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      #### The stsSeconds is the max-age of the Strict-Transport-Security header. If set to 0, would NOT include the header.
      traefik.http.middlewares.jellyfin-mw.headers.STSSeconds: "315360000"
      #### The stsIncludeSubdomains is set to true, the includeSubDomains directive will be
      #### appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains: "true"
      #### Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.
      traefik.http.middlewares.jellyfin-mw.headers.STSPreload: "true"
      #### Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.
      traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader: "true"
      #### Set frameDeny to true to add the X-Frame-Options header with the value of DENY.
      traefik.http.middlewares.jellyfin-mw.headers.frameDeny: "true"
      #### Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.
      traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff: "true"
      #### Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
      traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION: "1"
      #### The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This
      #### overrides the FrameDeny option.
      traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue: "'allow-from https://jellyfin.media.int.saphnet.xyz'"
      ## HTTP Service
      traefik.http.services.jellyfin-svc.loadBalancer.server.port: "8096"
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.media.int.saphnet.xyz
    volumes:
      - jellyfin-config:/config # Also, self-signed cert files in here
      - jellyfin-cache:/cache
      - media-server-movies:/media/movies
      - media-server-tv:/media/tv
      - media-server-anime:/media/anime
      - media-server-anime-movies:/media/anime-movies
    # Optional - alternative address used for autodiscovery
    networks:
      - media-server
      - web_bridge
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    init: true
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:5055:5055"
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.media.int.saphnet.xyz`)
      traefik.http.routers.jellyseerr.entrypoints: websecure
      traefik.http.routers.jellyseerr.tls: true
      traefik.http.routers.jellyseerr.tls.certresolver: letsencrypt
      traefik.http.routers.jellyseerr.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.jellyseerr.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.jellyseerr.service: jellyseerr-svc
      traefik.http.services.jellyseerr-svc.loadBalancer.server.port: "5055"
    environment:
      LOG_LEVEL: debug
      TZ: *timezone
    volumes:
      - jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: "20s"
      timeout: "3s"
      interval: "15s"
      retries: 3
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped

  flaresolverr: # Handles CloudFlare prompts for Prowlarr
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    # ports:
    #   - "8191:8191"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      LOG_FILE: "${LOG_FILE:-none}"
      LOG_HTML: "${LOG_HTML:-false}"
      CAPTCHA_SOLVER: "${CAPTCHA_SOLVER:-none}"
      TZ: *timezone
    volumes:
      - flaresolverr-config:/config
    networks:
      - media-server
    restart: unless-stopped
  
  prowlarr: # Handles trackers
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    # ports:
    #   - "9696:9696"
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.media.int.saphnet.xyz`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls: true
      traefik.http.routers.prowlarr.tls.certresolver: letsencrypt
      traefik.http.routers.prowlarr.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.prowlarr.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.prowlarr.service: prowlarr-svc
      traefik.http.services.prowlarr-svc.loadBalancer.server.port: "9696"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
    volumes:
      - prowlarr-config:/config
    networks:
      - media-server
      - web_bridge
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.5.2
    container_name: recyclarr
    user: "1000:1000"
    environment:
      TZ: *timezone
      RECYCLARR_CREATE_CONFIG: "true"
    volumes:
      - recyclarr-config:/config
    networks:
      - media-server
    restart: unless-stopped
    
  radarr: # For movies
    <<: *radarr
    container_name: radarr
    # ports:
    #   - "7878:7878"
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.media.int.saphnet.xyz`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: true
      traefik.http.routers.radarr.tls.certresolver: letsencrypt
      traefik.http.routers.radarr.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.radarr.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.radarr.service: radarr-svc
      traefik.http.services.radarr-svc.loadBalancer.server.port: "7878"
    volumes:
      - radarr-config:/config
      - media-server-movies:/movies # Jellyfin movies folder
      - seedbox-torrent-downloads:/downloads # Deluge complete downloads folder
  
  radarr-anime: # For anime movies
    <<: *radarr
    container_name: radarr-anime
    # ports:
    #   - "7879:7878"
    labels:
      traefik.enable: true
      traefik.http.routers.radarr-anime.rule: Host(`radarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.radarr-anime.entrypoints: websecure
      traefik.http.routers.radarr-anime.tls: true
      traefik.http.routers.radarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.radarr-anime.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.radarr-anime.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.radarr-anime.service: radarr-anime-svc
      traefik.http.services.radarr-anime-svc.loadBalancer.server.port: "7878"
    volumes:
      - radarr-anime-config:/config
      - media-server-anime-movies:/anime-movies # Jellyfin movies folder
      - seedbox-torrent-downloads:/downloads # Deluge complete downloads folder

  sonarr: # For shows
    <<: *sonarr
    container_name: sonarr
    # ports:
    #   - "8989:8989"
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.media.int.saphnet.xyz`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: true
      traefik.http.routers.sonarr.tls.certresolver: letsencrypt
      traefik.http.routers.sonarr.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.sonarr.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.sonarr.service: sonarr-svc
      traefik.http.services.sonarr-svc.loadBalancer.server.port: "8989"
    volumes:
      - sonarr-config:/config
      - media-server-tv:/tv
      - seedbox-torrent-downloads:/downloads
  
  sonarr-anime: # For anime
    <<: *sonarr
    container_name: sonarr-anime
    # ports:
    #   - "8990:8989"
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-anime.rule: Host(`sonarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.sonarr-anime.entrypoints: websecure
      traefik.http.routers.sonarr-anime.tls: true
      traefik.http.routers.sonarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.sonarr-anime.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.sonarr-anime.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.sonarr-anime.service: sonarr-anime-svc
      traefik.http.services.sonarr-anime-svc.loadBalancer.server.port: "8989"
    volumes:
      - sonarr-anime-config:/config
      - media-server-anime:/anime
      - seedbox-torrent-downloads:/downloads
  
  bazarr: # For subtitles
    <<: *bazarr
    container_name: bazarr
    # ports:
    #   - "6767:6767"
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.media.int.saphnet.xyz`)
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.tls: true
      traefik.http.routers.bazarr.tls.certresolver: letsencrypt
      traefik.http.routers.bazarr.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.bazarr.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.bazarr.service: bazarr-svc
      traefik.http.services.bazarr-svc.loadBalancer.server.port: "6767"
    volumes:
      - bazarr-config:/config
      - media-server-movies:/movies
      - media-server-tv:/tv
  
  bazarr-anime: # For anime subtitles
    <<: *bazarr
    container_name: bazarr-anime
    # ports:
    #   - "6768:6767"
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr-anime.rule: Host(`bazarr-anime.media.int.saphnet.xyz`)
      traefik.http.routers.bazarr-anime.entrypoints: websecure
      traefik.http.routers.bazarr-anime.tls: true
      traefik.http.routers.bazarr-anime.tls.certresolver: letsencrypt
      traefik.http.routers.bazarr-anime.tls.domains[0].main: media.int.saphnet.xyz
      traefik.http.routers.bazarr-anime.tls.domains[0].sans: "*.media.int.saphnet.xyz"
      traefik.http.routers.bazarr-anime.service: bazarr-anime-svc
      traefik.http.services.bazarr-anime-svc.loadBalancer.server.port: "6767"
    volumes:
      - bazarr-anime-config:/config
      - media-server-anime-movies:/anime-movies
      - media-server-anime:/anime

volumes:
  seedbox-files:
  jellyfin-config:
  jellyfin-cache:
  jellyseerr-config:
  flaresolverr-config:
  prowlarr-config:
  recyclarr-config:
  radarr-config:
  radarr-anime-config:
  sonarr-config:
  sonarr-anime-config:
  bazarr-config:
  bazarr-anime-config:
  media-server-movies:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/movies"
  media-server-tv:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/tv"
  media-server-anime:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/anime"
  media-server-anime-movies:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/jellyfin/anime-movies"
  seedbox-torrent-files:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_files"
  seedbox-torrent-downloads:
    driver_opts:
      <<: *nas_nfs_driver_opts
      device: ":/mnt/saphnet-nas1b/media-server/deluge/torrent_downloads"

networks:
  media-server: # Should be externally available
    name: media-server
  web_bridge:
    name: web_bridge
    external: true