# NOTE: If you want this to be accessible via Traefik, have a separate Compose file that refers to
# this file that has the labels included.
# This is the generic base version, with no labels. This can be run as-is, standalone.

services:
  glances:
    image: nicolargo/glances:latest@sha256:8b443a7fbd28198f1cd0ecceb9cc0b65827c71da25c67ba8bfed0b88568c771f
    pid: host
    network_mode: host # Make sure to set firewall rules accordingly!
    # ports:
    #   - "61208:61208"
    environment:
      GLANCES_OPT: "-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
      - /etc/hostname:/etc/hostname:ro
    restart: unless-stopped
