x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  foldingathome:
    image: ghcr.io/linuxserver/foldingathome:8.5.5@sha256:bdea49656192aa680311527a8a4608c0f57584cfe4c6ce3f71e2e7b8fd769853
    container_name: foldingathome
    deploy:
      resources:
        limits:
          cpus: "3.2"
    devices:
      - /dev/dri/:/dev/dri/
    # ports:
    #   - "7396:7396"
    labels:
      traefik.enable: "true"
      traefik.http.routers.fah.rule: Host(`fah.int.saphnet.xyz`)
      traefik.http.routers.fah.entrypoints: websecure
      traefik.http.routers.fah.tls: "true"
      traefik.http.routers.fah.tls.certresolver: letsencrypt
      traefik.http.routers.fah.tls.domains[0].main: fah.int.saphnet.xyz
      traefik.http.routers.fah.service: fah-svc
      traefik.http.services.fah-svc.loadBalancer.server.port: "7396"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
      MACHINE_NAME: docker-host-pve3
      CLI_ARGS:  #optional
      # Secrets to set in environment:
      ACCOUNT_TOKEN: "$ACCOUNT_TOKEN"
    volumes:
      - foldingathome:/config
    networks:
      - web_bridge
    restart: unless-stopped

volumes:
  foldingathome:

networks:
  web_bridge:
    name: web_bridge
    external: true
