# Be sure to define
# - DNS_NAMECHEAP_USERNAME
# - DNS_NAMECHEAP_API_KEY
# - CERTBOT_EMAIL
# - ED25519_PRIVATE_KEY_HEX

x-common:
  # Try to keep the order of this consistent, for Certbot's sake
  DOMAINS: &domains >-
    saphnet.xyz
    www.saphnet.xyz
    map.thevoidpact.xyz
    pterodactyl-node-public.saphnet.xyz
    jellyfin.saphnet.xyz
  ANUBIS: &anubis-environment # Default bind is 8923
    DIFFICULTY: "4"
    ED25519_PRIVATE_KEY_HEX: ${ED25519_PRIVATE_KEY_HEX}
    OG_PASSTHROUGH: "true"
    WEBMASTER_EMAIL: "homelab@saphnet.xyz"

services:
  nginx:
    container_name: nginx
    image: ghcr.io/anarchobooleanism/saphnet-nginx:v0.1.0
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    volumes:
      # Main conf file
      - ./nginx/proxies.conf:/etc/nginx/proxies.conf:ro
      # Certificate files
      - certbot-conf:/etc/letsencrypt:ro
    environment:
      - TZ=${TZ}
    networks:
      - web_bridge
  certbot:
    image: ghcr.io/anarchobooleanism/certbot-dns-namecheap:v1.0.0-certbotv5.2.2-1
    restart: unless-stopped
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ./certbot-entrypoint.sh:/certbot-entrypoint.sh:ro
      - ./certbot-entrypoint-helper.py:/certbot-entrypoint-helper.py:ro
    environment:
      TZ: ${TZ}
      DNS_NAMECHEAP_USERNAME: ${DNS_NAMECHEAP_USERNAME}
      DNS_NAMECHEAP_API_KEY: ${DNS_NAMECHEAP_API_KEY}
      CERTBOT_DOMAINS: *domains
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /etc/letsencrypt/live/saphnet.xyz/fullchain.pem ]"]
      interval: 20s
      retries: 12
      start_period: 10s
      timeout: 10s
    # Make sure certbot is run first if not yet, then renew certificates every 12 hours
    entrypoint: [ "/certbot-entrypoint.sh" ]
  # anubis-saphnet-main:
  #   container-name: anubis-saphnet-main
  #   image: ghcr.io/techarohq/anubis:v1.24.0-pre1
  #   environment: # Default bind is 8923
  #     <<: *anubis-environment
  #     COOKIE_DOMAIN: "saphnet.xyz"
  #     PUBLIC_URL: "https://saphnet.xyz"
  #     REDIRECT_DOMAINS: "saphnet.xyz"
  #     SERVE_ROBOTS_TXT: "true"
  #     TARGET: "http://nginx" # TODO: Change me
  #   healthcheck:
  #     test: ["CMD", "anubis", "--healthcheck"]
  #     interval: 5s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 500ms
  #   networks:
  #     - web_bridge
  anubis-thevoidpact-map:
    container_name: anubis-thevoidpact-map
    image: ghcr.io/techarohq/anubis:v1.24.0
    environment:
      <<: *anubis-environment
      COOKIE_DOMAIN: "thevoidpact.xyz"
      PUBLIC_URL: "https://map.thevoidpact.xyz"
      REDIRECT_DOMAINS: "map.thevoidpact.xyz"
      TARGET: "http://docker-host-pve4:63624"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    networks:
      - web_bridge
  anubis-jellyfin:
    container_name: anubis-jellyfin
    image: ghcr.io/techarohq/anubis:v1.24.0
    environment:
      <<: *anubis-environment
      COOKIE_DOMAIN: "saphnet.xyz"
      PUBLIC_URL: "https://jellyfin.saphnet.xyz"
      REDIRECT_DOMAINS: "jellyfin.saphnet.xyz"
      TARGET: "https://docker-host-pve3:8920"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    networks:
      - web_bridge

volumes:
  certbot-conf:

networks:
  web_bridge:
    name: web_bridge
