# To be run, and merged, with another host-specific file (e.g. control-server.yaml)
# Example command:
# docker compose -f base.yaml -f control-server.yaml up

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  docker-volume-rclone: &docker-volume-rclone # Is base service
    image: ghcr.io/anarchobooleanism/docker-volume-rclone:latest@sha256:e10ecf7949bcbc2e2753a0d42f3a2e8c8173f3a63d3fad03b97bf3fbb92c0324
    environment: &environment
      # Set TARGET_SUBDIR_NAME here
      # Set VOLUME_NAMES here, is space-delimited string, use ">-"
      RUN_ON_STARTUP: "false"
      CRON_ARGUMENTS: "0 */4 * * *" # At minute 0, every 4 hours
      # RCLONE_OPTIONS:
      TZ: *timezone
    volumes:
      - /var/lib/docker/volumes:/volumes:ro
      - nfs-target:/volumes-clone

volumes:
  nfs-target:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1a/docker-volume-backups"
