services:
  docker-volume-rclone:
    image: ghcr.io/anarchobooleanism/docker-volume-rclone:v0.1.0
    environment:
      TARGET_SUBDIR_NAME: docker-host-nginx
      VOLUME_NAMES: >-
        filestash_filestash
        guacamole_guac-db-data
        nginx-proxy-manager_data
        nginx-proxy-manager_letsencrypt
        nginx-proxy-manager_mysql
        pterodactyl-panel_database-data
        pterodactyl-panel_panel-data
        pterodactyl-panel_panel-logs
      RUN_ON_STARTUP: "false"
      CRON_ARGUMENTS: 0 */4 * * * # At minute 0, every 4 hours
      # RCLONE_OPTIONS:
      TZ: America/Los_Angeles
    volumes:
      - /var/lib/docker/volumes:/volumes:ro
      - nfs-target:/volumes-clone

volumes:
  nfs-target:
    driver_opts:
      type: "nfs"
      o: "addr=nas1.int-net.saphnet.xyz,nolock,soft,rw,nfsvers=4"
      device: ":/mnt/saphnet-nas1b/docker-volume-backups"