# Environment variables to set:
# - N8N_RUNNER_TOKEN, can be anything
# - MAIL_PASSWORD
# - POSTGRES_PASSWORD
# - POSTGRES_NON_ROOT_PASSWORD
# - ENCRYPTION_KEY, made with "openssl rand -hex 32"
# - TAILSCALE_IP, if you want to restrict access to n8n port to just Tailscale only (for external Traefik)

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  POSTGRES: &postgres
    POSTGRES_USER: &postgres_user "postgres"
    POSTGRES_NON_ROOT_USER: &postgres_non_root_user "postgres_nonroot"
    POSTGRES_DB: &postgres_db "n8n"
  MAIL: &mail
    N8N_SMTP_SENDER: "n8n <homelab@saphnet.xyz>"
    N8N_EMAIL_MODE: "smtp"
    N8N_SMTP_HOST: "mail.privateemail.com"
    N8N_SMTP_PORT: "465"
    N8N_SMTP_USER: "homelab@saphnet.xyz"
    N8N_SMTP_PASS: "${MAIL_PASSWORD}"
    N8N_SMTP_SSL: "true"

x-services: # Base instances of services to customize
  N8N_COMMON: &n8n_common
    image: n8nio/n8n:2.31.4@sha256:15091606d98f6d15bad10cb26bb937ccb47dfd9fee2bb7ae44c7061cba2e7a04
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - n8n-storage:/home/node/.n8n
    environment:
      <<: [*mail]
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: *postgres_db
      DB_POSTGRESDB_USER: *postgres_non_root_user
      DB_POSTGRESDB_PASSWORD: "${POSTGRES_NON_ROOT_PASSWORD}"
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: n8n-redis
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
      N8N_ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      # Other
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_HOST: n8n.int.saphnet.xyz
      N8N_PORT: "5678"
      N8N_PROTOCOL: https
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: external
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: "0.0.0.0"
      N8N_RUNNERS_AUTH_TOKEN: "${N8N_RUNNER_TOKEN}"
      N8N_NATIVE_PYTHON_RUNNER: "true"
      NODE_ENV: production
      WEBHOOK_URL: https://n8n.int.saphnet.xyz/
      GENERIC_TIMEZONE: *timezone
      TZ: *timezone
    networks: # When having more networks when merging this, be sure to include n8n_internal in the list too!
      - n8n_internal
    restart: unless-stopped

services:
  postgres:
    image: postgres:16@sha256:33f923b05f64ca54ac4401c01126a6b92afe839a0aa0a52bc5aeb5cc958e5f20
    container_name: n8n-postgres
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      <<: *postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_NON_ROOT_PASSWORD: "${POSTGRES_NON_ROOT_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - n8n_internal
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d n8n'] # Be sure to update this to reflect POSTGRES_USER and POSTGRES_DB!
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    container_name: n8n-redis
    volumes:
      - redis-storage:/data
    networks:
      - n8n_internal
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
  
  n8n:
    <<: *n8n_common
    container_name: n8n
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:5678:5678"
    networks:
      - n8n_internal
      - web_bridge
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.rule: Host(`n8n.int.saphnet.xyz`)
      traefik.http.routers.n8n.tls: "true"
      traefik.http.routers.n8n.entrypoints: websecure
      traefik.http.routers.n8n.tls.certresolver: letsencrypt
      traefik.http.routers.n8n.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.n8n.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.middlewares.n8n.headers.SSLRedirect: "true"
      traefik.http.middlewares.n8n.headers.STSSeconds: "315360000"
      traefik.http.middlewares.n8n.headers.browserXSSFilter: "true"
      traefik.http.middlewares.n8n.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.n8n.headers.forceSTSHeader: "true"
      traefik.http.middlewares.n8n.headers.SSLHost: int.saphnet.xyz
      traefik.http.middlewares.n8n.headers.STSIncludeSubdomains: "true"
      traefik.http.middlewares.n8n.headers.STSPreload: "true"
      traefik.http.routers.n8n.middlewares: n8n@docker
  
  n8n-worker:
    <<: *n8n_common
    container_name: n8n-worker
    depends_on:
      - n8n
    command: worker

  n8n-runner:
    image: n8nio/runners:2.31.4@sha256:ea1c18aeb644b673c927d19957269368a92de75fab7bb4748a79928c8ce12b6f
    container_name: n8n-runner
    depends_on:
      - n8n
    environment:
      N8N_RUNNERS_TASK_BROKER_URI: http://n8n-worker:5679
      N8N_RUNNERS_AUTH_TOKEN: "${N8N_RUNNER_TOKEN}"
    networks:
      - n8n_internal
    restart: unless-stopped

  n8n-homepage-api:
    image: ghcr.io/anarchobooleanism/n8n-homepage-api:v0.17.0@sha256:1a00e483937352aea550adaf840bb2342466526d3be70051c7d758668ecb7f4f
    container_name: n8n-homepage-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: *postgres_non_root_user
      POSTGRES_PASSWORD: "${POSTGRES_NON_ROOT_PASSWORD}"
      POSTGRES_HOST: n8n-postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: *postgres_db
      ROOT_PATH_PREFIX: "/api/homepage-custom" # Since Traefik serves the API at a custom path, we need to pass this to FastAPI so it can be aware of it
    networks:
      - n8n_internal
      - web_bridge
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n-homepage-api.rule: Host(`n8n.int.saphnet.xyz`) && Path(`/api/homepage-custom`)
      traefik.http.routers.n8n-homepage-api.tls: "true"
      traefik.http.routers.n8n-homepage-api.entrypoints: websecure
      traefik.http.routers.n8n-homepage-api.tls.certresolver: letsencrypt
      traefik.http.routers.n8n-homepage-api.tls.domains[0].main: int.saphnet.xyz
      traefik.http.routers.n8n-homepage-api.tls.domains[0].sans: "*.int.saphnet.xyz"
      traefik.http.middlewares.n8n-homepage-api-stripprefix.stripprefix.prefixes: /api/homepage-custom # Since our API listens at "/", we need to strip our path prefix out for it to work properly
      traefik.http.routers.n8n-homepage-api.middlewares: n8n-homepage-api-stripprefix
      traefik.http.routers.n8n-homepage-api.service: n8n-homepage-api-svc
      traefik.http.services.n8n-homepage-api-svc.loadbalancer.server.port: "8000" # FastAPI listens to 8000 by default

networks:
  n8n_internal:
  web_bridge:
    name: web_bridge
    external: true

volumes:
  db-storage:
  n8n-storage:
  redis-storage:
