# Be sure to define
# - VELOCITY_FORWARDING_SECRET
# - RCON_PASSWORD
# - SFTP_PASSWORD
# - TAILSCALE_IP
# Note: The actual environment variable, in the Velocity container, should be prefixed with "CFG_"

# Variables you'll want to frequently change
x-common:
  VELOCITY_VERSION: &velocity-version "3.4.0-SNAPSHOT" # See: https://papermc.io/downloads/velocity
  IMAGE_NAME: &image-name "itzg/mc-proxy:java21" # Set this to the Java version used by the Velocity version

services:
  velocity:
    image: *image-name
    container_name: velocity
    restart: unless-stopped
    environment:
      # For secrets
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      VELOCITY_FORWARDING_SECRET: "${VELOCITY_FORWARDING_SECRET}" # We will handle this ourselves
      # Velocity configuration
      TYPE: VELOCITY
      MEMORY: 512m
      VELOCITY_VERSION: *velocity-version
      VELOCITY_BUILD_ID: latest
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
    ports:
      - 25565:25565
      - ${TAILSCALE_IP:-0.0.0.0}:25575:25575
    volumes:
      - ./velocity-config/velocity.toml:/config/velocity.toml:ro
      - velocity-data:/server
    # As mc-proxy can only fill in certain types of files, we will set forwarding.secret ourselves
    # For last command, see: https://github.com/itzg/docker-mc-proxy/blob/master/Dockerfile
    command: >-
      '{ echo "${VELOCITY_FORWARDING_SECRET}" | tee "/config/forwarding.secret" } && /usr/bin/run-bungeecord.sh'
  velocity-sftp: 
    image: emberstack/sftp:build-5.1.72
    container_name: velocity-sftp
    restart: unless-stopped
    environment:
      SFTP_USERNAME: velocity-user
      SFTP_PASSWORD: ${SFTP_PASSWORD}
    volumes:
      - ./sftp-entrypoint.sh:/sftp-entrypoint.sh:ro
      - velocity-data:/home/velocity-user/sftp
      - sftp-ssh-data:/etc/ssh # For persistence of keys
    ports:
      - "${TAILSCALE_IP:-0.0.0.0}:2022:22"
    entrypoint: [ "/sftp-entrypoint.sh" ]

volumes:
  velocity-data:
  sftp-ssh-data:
