x-common:
  TIMEZONE: &timezone "America/Los_Angeles"

services:
  foldingathome:
    image: ghcr.io/linuxserver/foldingathome:8.5.6@sha256:8df6719cb3f18e622b5f0b0710e6c3c067ad0b055217c02633d6a904077cf43f
    container_name: foldingathome
    volumes:
      - foldingathome:/config
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: *timezone
      MACHINE_NAME: docker-host-pve3
      CLI_ARGS:  #optional
      # Secrets to set in environment:
      ACCOUNT_TOKEN: "$ACCOUNT_TOKEN"
    # ports:
    #   - "7396:7396"
    networks:
      - web_bridge
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.fah.rule: Host(`fah.int.saphnet.xyz`)
      traefik.http.routers.fah.entrypoints: websecure
      traefik.http.routers.fah.tls: "true"
      traefik.http.routers.fah.tls.certresolver: letsencrypt
      traefik.http.routers.fah.tls.domains[0].main: fah.int.saphnet.xyz
      traefik.http.routers.fah.service: fah-svc
      traefik.http.services.fah-svc.loadBalancer.server.port: "7396"
    deploy:
      resources:
        limits:
          cpus: "3.2"
    devices:
      - /dev/dri/:/dev/dri/

networks:
  web_bridge:
    name: web_bridge
    external: true

volumes:
  foldingathome:
