services:
  app:
    container_name: nginx-proxy-manager # Refer to the panel container this way
    image: jc21/nginx-proxy-manager:2.13.6
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "${TAILSCALE_IP:-0.0.0.0}:81:81" # Admin Web Port, restrict this to Tailscale IP if public-facing
      # Add any other Stream port you want to expose
      # - "21:21" # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "MariaDBUserPass"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: "true"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - npm_internal
      - web_bridge
    restart: unless-stopped

  db:
    image: jc21/mariadb-aria:10.11.5
    environment:
      MYSQL_ROOT_PASSWORD: "MariaDBRootPass"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "MariaDBUserPass"
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - npm_internal
    restart: unless-stopped

volumes:
  data:
  letsencrypt:
  mysql:

networks:
  npm_internal:
  web_bridge:
    name: web_bridge
    attachable: true
