services:
  vertd:
    image: ghcr.io/vert-sh/vertd:latest@sha256:492d17d1ce570e538a70efc3279c7208eb8b766889e8cedaa0aab93e29567a89
    container_name: vertd
    # For AMD/Intel GPUs, uncomment the "devices" section - then remove
    # or comment out the "deploy" section and the "runtime" string used
    # for NVIDIA GPUs.
    #
    devices:
      - /dev/dri
    #
    # For NVIDIA cards, keep the following section:
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]
    # ports:
    #   - "${PORT:-24153}:24153"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vertd.rule: Host(`vertd.int.saphnet.xyz`)
      traefik.http.routers.vertd.entrypoints: websecure
      traefik.http.routers.vertd.tls: "true"
      traefik.http.routers.vertd.tls.certresolver: letsencrypt
      traefik.http.routers.vertd.tls.domains[0].main: vertd.int.saphnet.xyz
      traefik.http.routers.vertd.service: vertd-svc
      traefik.http.services.vertd-svc.loadBalancer.server.port: "24153"
    environment:
      WEBHOOK_URL: "${WEBHOOK_URL}"
      WEBHOOK_PINGS: "${WEBHOOK_PINGS}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PUBLIC_URL: "${PUBLIC_URL}"
    networks:
      - web_bridge
    restart: unless-stopped

networks:
  web_bridge:
    name: web_bridge
    external: true
