# Configuration for Pterodactyl wings, to be paired with the panel
# This is intended to be used on docker-host-pve4

# Much of this comes from https://wiki.s5gi.com/guides/linux/pterodactyl_and_wings_dockerized
#                         https://technotim.live/posts/pterodactyl-game-server/
#                         https://docs.agamersgrind.com/guides/pterodactyl/creating-a-new-wings-node
#                         https://dev.to/marrouchi/the-challenge-about-ssl-in-docker-containers-no-one-talks-about-32gh

# Environment variables to set:
# - PTERODACTYL_TOKEN_ID
# - PTERODACTYL_TOKEN

x-common:
  TIMEZONE: &timezone "America/Los_Angeles"
  # INSTANCE_DOMAIN: &instance-domain "pterodactyl-node-main.int-net.saphnet.xyz"

services:
  wing:
    image: ghcr.io/pyrohost/elytra:1.4.0@sha256:7aba9b21bd60bf1eead7e7cf51d8277c4e6c8a64a5dd08f04d7aa39be273bbe6
    container_name: pterodactyl-wing # Refer to the panel container this way
    depends_on:
      init-config: # So that config.yml is tracked but still can be modified during runtime
        condition: service_completed_successfully
    volumes: # Mapping things to elytra, but source directories will remain same as before
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - wings-config:/etc/elytra
      - /var/lib/pterodactyl:/var/lib/pterodactyl # Some things still refer to /var/lib/pterodactyl...
      - /var/lib/pterodactyl:/var/lib/elytra
      - wings-logs:/var/log/elytra
      - /tmp/elytra:/tmp/elytra
      # - /run/elytra:/run/elytra # Currently disabled as machine-id is disabled, and NixOS doesn't have this as persistent
    environment:
      TZ: *timezone
      # For ease of setup, this is going to use root user.
      WINGS_UID: "0"
      WINGS_GID: "0"
      WINGS_USERNAME: root
    ports:
      # - "8443:443" # Is port 8443 on this IP, but 443 on the inside and 443 on the reverse proxy
      - "2022:2022" # SFTP port
    networks:
      - ptero0
      - web_bridge
    tty: true
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.pterodactyl-wing.rule: Host(`pterodactyl-node-main.int-net.saphnet.xyz`)
      traefik.http.routers.pterodactyl-wing.entrypoints: websecure
      traefik.http.routers.pterodactyl-wing.tls: "true"
      traefik.http.routers.pterodactyl-wing.tls.certresolver: letsencrypt
      traefik.http.routers.pterodactyl-wing.tls.domains[0].main: pterodactyl-node-main.int-net.saphnet.xyz
      traefik.http.routers.pterodactyl-wing.service: pterodactyl-wing-svc
      traefik.http.services.pterodactyl-wing-svc.loadBalancer.server.port: "443"

      # For Dynmap specifically
      traefik.http.routers.thevoidpact-map.rule: Host(`map-int.thevoidpact.xyz`)
      traefik.http.routers.thevoidpact-map.entrypoints: websecure
      traefik.http.routers.thevoidpact-map.tls: "true"
      traefik.http.routers.thevoidpact-map.tls.certresolver: letsencrypt
      traefik.http.routers.thevoidpact-map.tls.domains[0].main: map-int.thevoidpact.xyz
      traefik.http.routers.thevoidpact-map.service: thevoidpact-map-svc
      traefik.http.services.thevoidpact-map-svc.loadBalancer.server.url: http://host.docker.internal:63624
  
  init-config:
    build: ./init-config
    volumes:
      - ./init-config/config.yml.template:/config.yml.template
      - wings-config:/wings-config
    environment:
      PTERODACTYL_TOKEN_ID: "${PTERODACTYL_TOKEN_ID}"
      PTERODACTYL_TOKEN: "${PTERODACTYL_TOKEN}"
    entrypoint:
      - /bin/sh
      - -c
      - |
        envsubst '$$PTERODACTYL_TOKEN_ID,$$PTERODACTYL_TOKEN' \
          < /config.yml.template \
          > /wings-config/config.yml

# This is Wings' Network. We don't need much depth here, all you need to know, is
# that it allows the passthrough of the ports from Wings.
networks:
  web_bridge:
    name: web_bridge
    external: true
  ptero0:
    name: ptero0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ptero0

volumes:
  wings-config: # init-config creates config.yml, to be used by the wing service
  wings-logs:
